### ISSUE TITLE
[CT-315] CREATE VIEW statement column list includes invalid CAST()

### ISSUE THREAD

**Issue by brycebaker-centura** [dbt-labs/dbt-snowflake#100]
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?
Models that include a cast of a column only in the final CTE results in the CREATE VIEW statement performing the cast in the view column list. This applies to both hard-coded string literals and columns selected from another object.

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

Model code:
```
--test_model.sql
with test_unioned as (
        select '1' as column1
        union
        select '2' as column1
    )
    
    , final as (
        select cast(column1 as varchar)
        from test_unioned
    )
    
    select * from final
)
```

Resulting `dbt run` sql:
```
create
or replace view MY_DB.PUBLIC.test_model (
    CAST(COLUMN1 AS VARCHAR)
) as (
    with test_unioned as (
        select
            '1' as column1
        union
        select
            '2' as column1
    ),
    final as (
        select
            cast(column1 as varchar)
        from
            test_unioned
    )
    select
        *
    from
        final
);
```

To work around the issue, change model to cast columns before the final CTE as below:
```
with test_unioned as (
        select cast('1' as varchar) as column1
        union
        select cast('2' as varchar) as column1
    )
    
    , final as (
        select column1
        from test_unioned
    )
    
    select * from final
```

### Expected behavior
For Snowflake, CAST() in the column list of a CREATE VIEW statement is not valid syntax. dbt run should not build CREATE VIEW statements that include this function in the column list.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**The output of `dbt --version`:**
```
dbt --version
installed version: 1.0.3
   latest version: 1.0.3

Up to date!

Plugins:
  - snowflake: 1.0.0 - Up to date!
```

**The operating system you're using:**
Windows 10

**The output of `python --version`:**
Python 3.9.10

### Additional context
It would appear that computed columns with simple expressions are supported by Snowflake, but CAST() isn't included in this list of functions. (ref: https://community.snowflake.com/s/question/0D50Z00008ixGQKSA2/does-snowflake-supports-computed-columns-in-a-table-while-creating-table)

**Comment by jtcohen6** [comment]
@brycebaker-centura Thanks for opening the issue! Two quick questions:
- Do you have column-level `persist_docs` enabled for this view? I'm able to reproduce the issue, but only when I turn on that config.
- Is there a reason why you aren't specifying a column alias for the `CAST` expression? This works for me when I rename the column:
```sql
{{ config(persist_docs = {'columns': True}) }}

--test_model.sql
with test_unioned as (
        select '1' as column1
        union
        select '2' as column1
    )
    
    , final as (
        select cast(column1 as varchar) as new_column1
        from test_unioned
    )
    
    select * from final
```

**Comment by brycebaker-centura** [comment]
@jtcohen6 Exactly right - we do have persist_docs enabled. This also caused an issue when creating a view with dynamic pivots in which the column names weren't aliased properly. Seems this one isn't ready for prime time without a little more enhancement to handle those edge cases.

**Comment by jtcohen6** [comment]
@brycebaker-centura Totally fair.

To be clear, this isn't the default behavior—you have to opt into the `persist_docs` config for dbt to include the column schema in the `create view` statement.

I agree that a better version of this behavior would first check to see if there are any column comments at all, and exclude the column list if there are none. That change would happen here:

https://github.com/dbt-labs/dbt-snowflake/blob/fda11c2e822519996101d2c456a51570f4ed1c04/dbt/include/snowflake/macros/adapters.sql#L67-L72
