### ISSUE TITLE
[Bug] `test_python_model.py::TestSecrets::test_secrets` is failing in some scenarios

### ISSUE THREAD

**Issue by mikealfare** [dbt-labs/dbt-snowflake#1003]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

`test_python_model.py::TestSecrets::test_secrets` fails on some runs.

### Expected Behavior

Tests should pass.

### Steps To Reproduce

https://github.com/dbt-labs/dbt-snowflake/actions/runs/8858753649/job/24327779018

### Relevant log output

```shell
Database Error in model secret_python_model (models/secret_python_model.py) 509007 (22023): SQL compilation error: Integrations do not allow secret '***.TEST17142092113402529018_TEST_PYTHON_MODEL.TEST_SECRET'. compiled Code at target/run/test/models/secret_python_model.py
```

### Environment

```markdown
- OS: ubuntu-latest, macos-12
- Python: py38
- dbt-core:
- dbt-snowflake: `main`
```

**Comment by colin-rogers-dbt** [comment]
Suggested order of operations:
* Better understand external integrations / secrets 
* Move to it's own job that runs serially (similar to what we did in dbt-redshift)
