### ISSUE TITLE
[CT-331] Views with persist_docs on columns: check to see if any comments first

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-snowflake#102]
From https://github.com/dbt-labs/dbt-snowflake/issues/100#issuecomment-1058250845:

> I agree that a better version of this behavior would first check to see if there are any column comments at all, and exclude the column list if there are none. That change would need to happen here:

https://github.com/dbt-labs/dbt-snowflake/blob/fda11c2e822519996101d2c456a51570f4ed1c04/dbt/include/snowflake/macros/adapters.sql#L67-L72

**Comment by jkjetty** [comment]
Hey @jtcohen6 I'm happy to dig into this as my first issue if that's alright.  

If I understand correctly, we want to avoid calling `get_persist_docs_column_list()` if none of the columns are going to have comments injected from the schema config. So I need to wrap this line with a check if any of `query_columns` has a `model_column[column_name]['description']` available for it? 

https://github.com/dbt-labs/dbt-snowflake/blob/fda11c2e822519996101d2c456a51570f4ed1c04/dbt/include/snowflake/macros/adapters.sql#L70

If there aren't any comments to be included, then we will leave out the column list altogether, right?

**Comment by Fleid** [comment]
Hi @jkjetty, #161 was merged some time ago.
Do you still plan to take a stab at this one? No pressure at all, just doing some housekeeping ;)

**Comment by jkjetty** [comment]
@Fleid I am not planning on taking it on, thanks for checking in.
