### ISSUE TITLE
[Bug] macros have no way to execute a query with a contained semicolon.

### ISSUE THREAD

**Issue by AartBluestoke** [dbt-labs/dbt-snowflake#1052]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

i have a macro for deploying a task.

when a macro passesed a script to run, it forcably splits it by semicolon

```

create or replace task lmg.unload_daily_scannd

begin
drop table if exists tmp_data;
create temporary table tmp_data         as select 1 ;
end

```

is passed to snowflake piecemeal:

```
create or replace task my_data_task
begin
drop table if exists tmp_data;
```
then presumably it would continue, but the above is a syntax error. 
```
create table tmp_data as select 1 ;
```
This occurs because 
https://github.com/dbt-labs/dbt-snowflake/blob/87a6e808dfb025df1eeef3741ad3822635249889/dbt/adapters/snowflake/connections.py#L496

which redirects to
https://github.com/dbt-labs/dbt-snowflake/blob/87a6e808dfb025df1eeef3741ad3822635249889/dbt/adapters/snowflake/connections.py#L443C11-L443C78
snowflake.connector.util_text.split_statements(sql_buf)

split_statements takes an optional second parameter (which defaults to semicolon) to split on, but has a single override for transactions - i suggest the fix is that there is an option to pass a custom split token, or even to skip the split and execute what was passed without splitting.

splits by semicolon

### Expected Behavior

if my macro says 
    {% call statement(name="main") %}
        {{ raw_statement }}
    {% endcall %}

then if raw_statement is something i can copy-paste to snowflake without a syntax error should be executed without problem, and not split into multiple smaller statements which then fail.

### Steps To Reproduce

    {% materialization tasktest, adapter='default', supported_languages=['sql', 'python']%}

        {% call statement(name="main") %}
    create or replace task testTask as
    begin
      drop table if exists public.tempTable_task_test;
      create table public.tempTable_task_test as select 1;
    end;
        {% endcall %}

    {% endmaterialization %}

and a sql file of only

   {{ config(    materialized="tasktest") }}

builds fails on the snowflake side with

![image](https://github.com/dbt-labs/dbt-snowflake/assets/1892829/97e00f1f-a1ef-441c-8d99-ef210a26044d)

### Relevant log output

```shell
07:26:45  Completed with 1 error and 0 warnings:
07:26:45
07:26:45    Database Error in model taskTesting (models\taskTesting.sql)
  001003 (42000): SQL compilation error:
  syntax error line 3 at position 50 unexpected '<EOF>'.
  compiled Code at target\run\dbt_core\models\taskTesting.sql
```

### Environment

```markdown
- OS: windows 11
- Python: 3.12.1
- dbt-core: 1.7.11 
- dbt-snowflake: 1.7.3
```

**Comment by amychen1776** [comment]
Unfortunately at this time, we are unable to prioritize this request.

**Comment by paulbenschmidt** [comment]
In case it helps anyone, [this other thread](https://github.com/dbt-labs/dbt-snowflake/issues/875#issuecomment-1874616981) also addresses the same problem for procedures. The trick is to wrap it in `$$`.
