### ISSUE TITLE
[Feature] Replace underscores with hyphens in account ids

### ISSUE THREAD

**Issue by colin-rogers-dbt** [dbt-labs/dbt-snowflake#1069]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

If an account uses underscores in their accound id it can cause issues with various url and auth libraries since it's not compliant with most specs. Per [snowflake's docs](https://docs.snowflake.com/en/user-guide/admin-account-identifier#account-name) we can replace underscores with hyphens so we should default to doing that.

**Comment by jtcohen6** [comment]
I got there first :)
- https://github.com/dbt-labs/dbt-snowflake/issues/1068
