### ISSUE TITLE
[Feature] Refresh mode for dynamic tables

### ISSUE THREAD

**Issue by matsavage** [dbt-labs/dbt-snowflake#1086]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When working with dynamic tables, there is no option to specify the "refresh mode" for the table on creation, which is something we would like to do with our models.

https://docs.snowflake.com/en/sql-reference/sql/create-dynamic-table

This is useful to us, as some of our tables are not automatically "INCREMENTAL" refresh and fall-back to "FULL", and we would like to override this

### Describe alternatives you've considered

Looked at a pre-hook to generate a table, but this is very unsatisfactory

### Who will this benefit?

Users of Dynamic tables in Snowflake

### Anything else?

I don't think this is a huge piece of functionality to add, but it feels like there is a lot of overhead wrt complexity of the project and getting an environment set up to test.

**Comment by matsavage** [comment]
I have added a (draft) PR with the bulk of the changes, but access to a non-work, non-locked down instance of snowflake to test against will be a hinderance from here.

**Comment by jtcohen6** [comment]
Hey @matsavage - thanks for the issue! I think we've already got some work in flight to address this:
- https://github.com/dbt-labs/dbt-snowflake/pull/1081

As a continuation of this past issue / community PR:
- https://github.com/dbt-labs/dbt-snowflake/issues/868
- https://github.com/dbt-labs/dbt-snowflake/pull/893

If you want to give that branch a try, before we merge & release:
```
pip install git+https://github.com/dbt-labs/dbt-snowflake.git@dynamic-table-parameters
```

**Comment by jtcohen6** [comment]
I'm going to close this issue, as I believe it's a duplicate with the ones linked above, but please let me know if you disagree!

**Comment by matsavage** [comment]
Thanks, this looks like it does it!
