### ISSUE TITLE
[Bug] Support Vector data types for macro `snowflake__get_columns_in_relation` 

### ISSUE THREAD

**Issue by chamilton61** [dbt-labs/dbt-snowflake#1098]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When trying to run an incremental load referencing a table that has a column that is cast as a VECTOR data type, I get the following error: `Could not interpret data_type "VECTOR(FLOAT, 1536)": could not convert "FLOAT" to an integer`

This appears to be due to the `from_description` Column function [here](https://github.com/dbt-labs/dbt-adapters/blob/main/dbt/adapters/base/column.py#L130) expecting only integers within parenthesis.

### Expected Behavior

Expected column data type to be properly parsed and reproduced in the incremental table.

### Steps To Reproduce

do `dbt run` on a model that has an incremental load materialization and has a column that is the VECTOR data type

### Relevant log output

```shell
15:40:11  Snowflake adapter: Error running SQL: macro get_columns_in_relation
15:40:11  Snowflake adapter: Rolling back transaction.
15:40:11  On <model name>: Close
15:40:11  Runtime Error in model <model name> (<model name>.sql)
  Could not interpret data_type "VECTOR(FLOAT, 1536)": could not convert "FLOAT" to an integer
```

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS
- Python:  3.11.7
- dbt-core: 1.8.3
- dbt-snowflake: 1.8.3
```

### Additional Context

suspected cause of the issue: 
https://github.com/dbt-labs/dbt-snowflake/blob/2576a08379e248d393b9a698e58fac0d32c23648/dbt/include/snowflake/macros/adapters.sql
https://github.com/dbt-labs/dbt-adapters/blob/main/dbt/adapters/base/column.py#L130

**Comment by cgarretty** [comment]
+1 - we're also being impacted by this.

**Comment by brandonpeebles** [comment]
+1 — also been dealing with this error trying to reference source iceberg tables that contain `Array` or `Object` data types.

**Comment by dassowmd** [comment]
+1 This is blocking the VECTOR datatype in snowflake

**Comment by mbdataminr** [comment]
+1 Any update on when this will be released?

**Comment by JaydanPB** [comment]
+1 This prevents incremental models which use Cortex embeddings. Any updates on release date?

**Comment by yuanzheng319** [comment]
+1 this is blocking Snowflake Cortex embeddings 
` Could not interpret data_type "VECTOR(FLOAT, 1024)": could not convert "FLOAT" to an integer
`

**Comment by ioleary1** [comment]
+1 Running into this issue as well. Materializing the model with `--full-refresh` works fine but fails with both `merge` and `append`
`Could not interpret data_type "VECTOR(FLOAT, 1024)": could not convert "FLOAT" to an integer`
