### ISSUE TITLE
[Bug] target_lag < 1 minute throws an error

### ISSUE THREAD

**Issue by noel** [dbt-labs/dbt-snowflake#1217]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

According to the [official dbt docs](https://docs.getdbt.com/reference/resource-configs/snowflake-configs#target-lag), target_lag of < 1 minute should be possible, but when I try this in dbt-snowflake==1.8.4 I get the following error:

```
002755 (22023): SQL compilation error: Invalid TARGET_LAG value '30 seconds'. Dynamic Tables do not support lag values under 60 second(s).
```

### Expected Behavior

30 second target lag should work

### Steps To Reproduce

Create a model with the following configuration:

```
{{ config(
    materialized = 'dynamic_table',
    snowflake_warehouse = '<my_wh>',
    target_lag = '30 seconds',
) }}
```

run the model 

### Relevant log output

```shell
002755 (22023): SQL compilation error: Invalid TARGET_LAG value '30 seconds'. Dynamic Tables do not support lag values under 60 second(s).
```
```


### Environment

```markdown
- OS: Linux
- Python: 3.10.12
- dbt-core: 1.8.7
- dbt-snowflake: 1.8.4
```

**Comment by amychen1776** [comment]
Hi @noel , Snowflake does not support a lag of less than 1 minute. It's in their official documentation https://docs.snowflake.com/en/sql-reference/sql/alter-dynamic-table 

Due to this - I'm closing this issue out. I'll make a note in our documentation to be clear that while 30 minutes is supported, 30 seconds (and anything under a minute) is not due to Snowflake's limitations.

**Comment by noel** [comment]
oh, thank you for clarifying, I had not seen this

```
The minimum value is 1 minute. If a dynamic table A depends on another dynamic table B, the minimum lag for A must be greater than or equal to the lag for B.
```

So I guess the point of seconds is to be able to do something like `90 seconds` not as I tried to do with 30

**Comment by amychen1776** [comment]
That's correct!
