### ISSUE TITLE
[CT-443] Potentially sensitive data can be written to logfiles on incremental model failure

### ISSUE THREAD

**Issue by verhey** [dbt-labs/dbt-snowflake#123]
### Describe the bug
When a merge statement fails on Snowflake with a duplicate row, Snowflake will return the data from the row that failed in the format `Duplicate row detected during DML action Row Values: [12345, "col_a_value", "col_b_value", "col_c_value", "etc"...]` 

Since dbt reports those errors back to the user via `stdout` and logs them in `dbt.log` when such an error occurs, data from the warehouse is written to disk, potentially multiple times if dbt is run from a process capturing `stdout` (like many orchestrators). If the incremental model processes sensitive data, this is a way for said sensitive data to find its way into logfiles, which is a pattern [discouraged by OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html#data-to-exclude)

This error reporting behavior can be suppressed in Snowflake via the [ERROR_ON_NONDETERMINISTIC_MERGE](https://docs.snowflake.com/en/sql-reference/parameters.html#error-on-nondeterministic-merge) parameter but I don't really want to modify the behavior of the merge, just modify the logging behavior. 

Logging this in `dbt-snowflake` instead of `dbt-core` because I think it's more of a quirk of Snowflake than it is a core dbt problem. dbt is just reporting the error returned from the DB, and I'm not sure if other DBs supported by dbt behave this way on a failed merge. The error message from Snowflake is helpful, but I think it's being _too_ helpful here. 

### Steps To Reproduce
1. Create a incremental model: 
```sql
-- fail_merge.sql
{{ config(
    materialized='incremental',
    unique_key='id'
) }}

with data as (
    SELECT $1 id, $2 name FROM (
        VALUES (1, 'one'), (2, 'two'), (3, 'three')
    )
)
select * from data
```
2. Run the incremental model once. 
```
❯ dbt run -m fail_merge
Running with dbt=0.21.0
Found 231 models, 126 tests, 20 snapshots, 0 analyses, 188 macros, 0 operations, 0 seed files, 108 sources, 0 exposures

10:20:26 | Concurrency: 6 threads (target='dev_snowflake')
10:20:26 | 
10:20:26 | 1 of 1 START incremental model analytics.fail_merge.................. [RUN]
10:20:28 | 1 of 1 OK created incremental model analytics.fail_merge............. [SUCCESS 1 in 1.69s]
10:20:28 | 
10:20:28 | Finished running 1 incremental model in 9.08s.

Completed successfully
```
3. Modify your incremental model to return a duplicate row 
```sql
-- fail_merge.sql after edit
{{ config(
    materialized='incremental',
    unique_key='id'
) }}

with data as (
    SELECT $1 id, $2 name FROM (
        VALUES (1, 'one'), (2, 'two'), (3, 'three'), (1, 'one')
    )
)
select * from data
```
4. Run your incremental model again and note the presence of the data that failed the merge in `stdout` and `dbt.log`
```
❯ dbt run -m fail_merge
Running with dbt=0.21.0
Found 231 models, 126 tests, 20 snapshots, 0 analyses, 188 macros, 0 operations, 0 seed files, 108 sources, 0 exposures

10:26:09 | Concurrency: 6 threads (target='dev_snowflake')
10:26:09 | 
10:26:09 | 1 of 1 START incremental model analytics.fail_merge.................. [RUN]
10:26:12 | 1 of 1 ERROR creating incremental model analytics.fail_merge......... [ERROR in 3.22s]
10:26:12 | 
10:26:12 | Finished running 1 incremental model in 10.86s.

Completed with 1 error and 0 warnings:

Database Error in model fail_merge (models/analytics/fail_merge.sql)
  100090 (42P18): Duplicate row detected during DML action
  Row Values: [1, "one"]
  compiled SQL at target/run/launchdarkly/models/analytics/fail_merge.sql

Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```
```
❯ tail -n 8 logs/dbt.log
2022-03-31 17:26:13.020221 (MainThread): Database Error in model fail_merge (models/analytics/fail_merge.sql)
2022-03-31 17:26:13.020394 (MainThread):   100090 (42P18): Duplicate row detected during DML action
2022-03-31 17:26:13.020558 (MainThread):   Row Values: [1, "one"]
2022-03-31 17:26:13.020717 (MainThread):   compiled SQL at target/run/launchdarkly/models/analytics/fail_merge.sql
2022-03-31 17:26:13.020883 (MainThread): 
Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
2022-03-31 17:26:13.021132 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11377be20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11377bfa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11377b460>]}
2022-03-31 17:26:13.021412 (MainThread): Flushing usage events
```

### Expected behavior
Contents of `Row Values: [...]` are not written to disk and/or logged to `stdout`. While the example above didn't include sensitive data, if the model processed sensitive data it would, and ideally that data in the warehouse should not be logged. 

### Screenshots and log output
See "Steps To Reproduce"

### System information
**The output of `dbt --version`:**
```
❯ dbt --version
installed version: 0.21.0
   latest version: 1.0.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 0.21.0
```

**The operating system you're using:**
`macOS Monterey 12.3`

**The output of `python --version`:**
```
❯ python --version
Python 3.8.12
```
### Additional context
[Slack thread](https://getdbt.slack.com/archives/CJN7XRF1B/p1648605549929909)

**Comment by dataders** [comment]
@verhey thanks for logging this! My 5 min take is that I think we can handle this scenario by catching the presence of the error, the manipulating the message before logging it with the debugger where at least you could tell the user how many rows are duplicate? in my example below I'm not manipulating the string just giving a new string. hopefully this gives you a start?

#### dataders's super simple example

```python
if "100090 (42P18): Duplicate row detected during DML action" in msg:
    logger.debug(" 100090 (42P18): Duplicate row detected during DML action!")
```

Not sure if you've contributed to dbt-core or dbt-snowflake before, but [this guide](https://github.com/dbt-labs/dbt-snowflake/blob/main/CONTRIBUTING.MD#running-dbt-snowflake-in-development) is a great place to get started

#### similar error handling done previously

https://github.com/dbt-labs/dbt-snowflake/blob/184eaeb3fa65fb4090d811ea0fa6b7da3ea94574/dbt/adapters/snowflake/connections.py#L226-L227
