### ISSUE TITLE
[BUG] 'str' object has no attribute 'get' with externalbrowser authentication

### ISSUE THREAD

**Issue by javierpe27** [dbt-labs/dbt-snowflake#1249]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Hello, I am facing an issue, all of a sudden i cannot run my dbt models on snowflake using dbt-snowflake 1.8.3 I keep getting this error. I first thought that the profiles file was the issue but i have been using the same profile for months so it cannot be, I use externalbrowser authentication with sso but it never gets to even open the browser, the profiles file is also being read from the right path when doing dbt debug any idea?

Dbt run: 

16:41:59  Running with dbt=1.8.8

16:41:59  Registered adapter: snowflake=1.8.3

16:42:00  Unable to do partial parsing because profile has changed

16:42:02  Found 26 models, 1 seed, 10 sources, 749 macros

16:42:02 

16:42:02 

16:42:02  Finished running  in 0 hours 0 minutes and 0.02 seconds (0.02s).

16:42:02  Encountered an error:

Runtime Error

  Database error while listing schemas in database "T"

  Database Error

    'str' object has no attribute 'get'

### Expected Behavior

Open the browser and login, however the browser is not being opened 

### Steps To Reproduce

OS: windows 10 with Wsl 
 dbt=1.8.8
adapter: snowflake=1.8.3
Python:3.10

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-snowflake:
```

**Comment by amychen1776** [comment]
@javierpe27 did you make any code changes before this started to fail?

**Comment by javierpe27** [comment]
No change, I pull the code directly from the repo and it works for my colleagues, so it seems it is a dbt specific error in my machine. I tried uninstalling and installing again but it didn't solve it.

**Comment by amychen1776** [comment]
@javierpe27 Could you try creating a new valid profiles.yml and pointing dbt to it? Just in case there is something related because your error message also calls out that the profiles.yml might have changed. 

Also are you on the same version of Windows as your coworker?

**Comment by colin-rogers-dbt** [comment]
@javierpe27 can you run the following command and share the output:
`dbt debug --connection log-level debug`

**Comment by michael-urrutia** [comment]
Have you tried upgrading to the latest version of `dbt-snowflake`, `1.8.4` to try and reproduce?

**Comment by AmiriMc** [comment]
> Have you tried upgrading to the latest version of `dbt-snowflake`, `1.8.4` to try and reproduce?

Me and my co-worker are using 1.8.4 and we're having the same issue when trying to connect via SSO.

**Comment by javierpe27** [comment]
Hi @michael-urrutia yes i just updated to 1.8.4 and i get the same error

**Comment by AmiriMc** [comment]
Hey @javierpe27, what version of WSL are you using? Can you post it for us?

My setup:
- OS: WSL running in Windows 10
- From `dbt debug`: 
- os info: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.35
- dbt version: 1.8.9
-  python version: 3.10.12
- snowflake adapter version: 1.8.4

**Comment by javierpe27** [comment]
Hi @colin-rogers-dbt
This is the output 

08:29:46  Registered adapter: snowflake=1.8.3

08:29:46  Acquiring new snowflake connection 'debug'

08:29:46  Using snowflake connection "debug"

08:29:46  On debug: select 1 as id

08:29:46  Opening a new connection, currently in state init

08:29:46  Snowflake adapter: Error running SQL: select 1 as id

08:29:46  Snowflake adapter: Rolling back transaction.

08:29:46  On debug: No close available on handle

08:29:46    Connection test: [ERROR]

 

08:29:46  1 check failed:

08:29:46  dbt was unable to connect to the specified database.

The database returned the following error:

 

  >Database Error

  'str' object has no attribute 'get'

 

Check your database credentials and try again. For more information, visit:

https://docs.getdbt.com/docs/configure-your-profile

**Comment by AmiriMc** [comment]
Hey @javierpe27 ,

We were able to fix this bug. Shout out to Loran! It turns out it is a caching issue; it was caching temporary Snowflake credentials.

How we fixed it:
- Clear the cache by running command: `rm ~/.cache/snowflake/temporary_credential.json`

**Comment by javierpe27** [comment]
Hi @AmiriMc thanks it worked!
