### ISSUE TITLE
Use cluster by keys in merge for faster incremental updates

### ISSUE THREAD

**Issue by bastienboutonnet** [dbt-labs/dbt-snowflake#13]
### Description
dbt-labs/dbt#1689 brought the ability for users to leverage Snowflake's clustering in dbt.
We recently realised that maybe on clustered tables we could make merge operations faster by using the cluster keys provided on the model. After testing it via a custom materialisation in our macros we really saw a huge improvement!

The main advantage is that when you feed the keys that are used in the clustering of the table, Snowflake does not cause a full table scan and it's able to directly target the cluster/partition where things should be merged. Since the table is clustered, homing on the right partition is a breeze.

### Additional context
Snowflake specific

### Who will this benefit?
Anyone on snowflake with large tables who leverages clustering in dbt.

I'd be more than happy to contribute this functionality back to dbt as it's fairly simple. 
It would basically consist in adding a test for whether `cluster_by_keys` are provided and adding them kind of like the following snipped.

```
        {% if cluster_by_keys is not none %}
            {% for key in cluster_by_keys %}
                and DBT_INTERNAL_SOURCE.{{key}} = DBT_INTERNAL_DEST.{{key}}
            {% endfor %}
        {% endif %}
```

If this is something you guys would be insterested in I can put up a PR fairly quickly. Would love, first to hear your thoughts, and discuss potential caveats.

**Comment by rumbin** [comment]
See also discussion on discourse:
https://discourse.getdbt.com/t/incremental-model-use-db-cluster-column/1946

**Comment by rumbin** [comment]
See also discussion on discourse:
https://discourse.getdbt.com/t/incremental-model-use-db-cluster-column/1946
