### ISSUE TITLE
Snowflake queueing causes keypair auth'd connections to fail

### ISSUE THREAD

**Issue by drewbanin** [dbt-labs/dbt-snowflake#14]
### Describe the feature
Snowflake keypair connections have 10 seconds to execute before the embedded JWT token expires. If many concurrent queries are opened against Snowflake _when using keypair auth_, Snowflake can fail to open connections with this error:

```
Failed to connect to DB: db.snowflakecomputing.com:443. JWT token is invalid.
```

I don't think there's too much we can do on dbt's side of things to prevent this, but we can consider doing the following things:
 - catch this error and retry opening the connection after some timeout
 - provide better tooling for users to understand how queueing affects dbt invocations
   - This could be as simple as a handy Snowflake query you can run to analyze concurrently running dbt queries over time
   - It would be awesome to include queued time in the logs or `run_results.json` file if Snowflake makes it available to us

### Steps To Reproduce
0. Configure a Snowflake connection with keypair auth
1. Create a sample project with 64 models in it
2. Run `dbt run --threads 64`

### Expected behavior
TBD. We can address this issue with:
 - Better docs and tooling
 - Retries
 - More information in dbt log output

### System information
**Which database are you using dbt with?**
- [x] snowflake

**The output of `dbt --version`:**
Any

**The operating system you're using:**
Any

**The output of `python --version`:**
Any

**Comment by jtcohen6** [comment]
Resolved by #6
