### ISSUE TITLE
[CT-573] Can't specify application using Snowflake profile yaml

### ISSUE THREAD

**Issue by fivetran-fedorabramov** [dbt-labs/dbt-snowflake#148]
### Describe the feature
I connect to Snowflake using profiles.yaml file and I want to specify application parameter to connection (https://docs.snowflake.com/en/user-guide/jdbc-parameters.html#application). I don't see this ability in your documentation (https://docs.getdbt.com/reference/warehouse-profiles/snowflake-profile)

### Describe alternatives you've considered
Probably it might be any additional parameter supported by Snowflake

### Additional context
N/A

### Who will this benefit?
It will be useful for users who want to differentiate utilization/cost on Snowflake between their applications

### Are you interested in contributing this feature?
I am not authorized to deal with such matters in my company

**Comment by anthu** [comment]
The application is explicitly set to `dbt` here: https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/adapters/snowflake/connections.py#L272

What's the use-case are you having in mind?

**Comment by fivetran-fedorabramov** [comment]
Thank you for answer. We have several business applications that use dbt. And our customer wants to know how each of them uses his warehouse resources.

**Comment by anthu** [comment]
I see. Have you checked out the `query_tag` parameter? It's a common way to separate queries/usage based on that tag.

Here are the documentations:
https://docs.getdbt.com/reference/warehouse-profiles/snowflake-profile#query_tag
https://docs.snowflake.com/en/sql-reference/parameters.html#query-tag

And here is a short explanation video on how to use them:
https://www.youtube.com/watch?v=e2-AfNvq2Ts

I hope that helps.

**Comment by jtcohen6** [comment]
I was going to say much the same thing as @anthu!

My sense is that this `application` parameter is really just for Snowflake's internal metrics. We set this  to `dbt` so that Snowflake is able to get a sense, on their end, of warehouse usage coming from dbt. It's not accessible to end users in the same ways and places that `query_tag` is.

I'm going to close this issue, but do let me know if I'm missing an important detail, or something that might be possible with the `application` field that isn't possible with `query_tag`.

**Comment by fivetran-fedorabramov** [comment]
Thanks, okay. Will investigate about query_tag

**Comment by NehaNRane** [comment]
Hi @anthu @jtcohen6,

I see there's already an ongoing discussion regarding updating the application name in the client driver. I'd like to contribute to this effort as I believe it's crucial for enhancing the visibility of our product (which uses dbt-core) within Snowflake environments.

I've noticed that the application name in the client driver is currently hard-coded to "dbt". Given the importance of accurately representing our product's usage within Snowflake environments, I propose making this application name configurable.
 
By allowing users to specify a custom application name through a configuration option in the dbt-snowflake adapter, we can provide greater flexibility and customization. This change would enable users to tailor the application name to better reflect their organization's identity and enhance visibility within Snowflake environments.
 
I'm eager to contribute to this effort and am willing to take on the implementation. Your feedback and guidance on this proposed enhancement would be greatly appreciated.
 
Looking forward to contributing to the enhancement of dbt-snowflake!

**Comment by dbeatty10** [comment]
Thanks for touching base about this @NehaNRane !

Our answer today is the same as [last time](https://github.com/dbt-labs/dbt-snowflake/issues/148#issuecomment-1114635758) (May 2, 2022). Namely, the `application` parameter is intentionally hard-coded and not accessible to end users.

But as described in https://github.com/dbt-labs/dbt-snowflake/issues/148#issuecomment-1113724993, [`query_tag`](https://docs.getdbt.com/reference/warehouse-profiles/snowflake-profile#query_tag) is accessible and configurable to end users, and we recommend using that instead.

So I'm going to close this issue and the associated pull requests as not planned.
