### ISSUE TITLE
[CT-689] Store Successful Tests along with Failures using --store-failure flag

### ISSUE THREAD

**Issue by brittianwarner** [dbt-labs/dbt-snowflake#164]
### Describe the feature
As a dbt user, I would like to store all tests including passes and failures.  As part of a DQ reporting initiative, we want to be able to see percentage of successful tests compared to failures.  We know we could possible customize the output to do this but am wondering if this can be built into the `--store-failures` flag and possibly a field in the created table for status (pass vs failure).  

### Describe alternatives you've considered
Create a service that reads dbt output to store test results.

### Additional context
This is more for individuals who have a requirement to report on DQ metrics.  It seems like most of the functionality is in place, however it is not clear on whether we can store successful tests along with failures.  Please, advise if I am missing something. 

### Who will this benefit?
Anyone reporting on data quality in a regulated environment. 

### Are you interested in contributing this feature?
Yes, the best I can.

**Comment by hiattp** [comment]
@brittianwarner Should we raise this in dbt core instead?

**Comment by jtcohen6** [comment]
Thanks for reopening in https://github.com/dbt-labs/dbt-core/issues/5313; I'm going to close the issue here
