### ISSUE TITLE
[CT-704] [CT-703] [Feature] Display the Query ID in the printed logs when dbt runs

### ISSUE THREAD

**Issue by mpavillet** [dbt-labs/dbt-snowflake#165]
### Is this your first time opening an issue?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)

### Describe the Feature

I have been hunting down some performance issues recently and was having a hard time finding the query related to my model.
It would be extremely useful to display the query_id in the printed logs:
![image](https://user-images.githubusercontent.com/18498445/171298126-957fa20b-ac1e-46a8-a5b2-95ca598d0604.png)

### Describe alternatives you've considered

I am using Snowflake and look for queries fired by DBT using the search history (or query history tables)

### Who will this benefit?

Any dbt user who would like to get more insights into the query fired by dbt. 
It depends on the database but will usually give useful information such as the explain plan. 
This helps anyone who needs to investigate what's happening in the database.

### Are you interested in contributing this feature?

I'd need help on where to start but happy to help!

### Anything else?

https://getdbt.slack.com/archives/C2JRTGLLS/p1653515842370159

**Comment by mpavillet** [comment]
Thank you for the answer Jeremy. I am able to find the query id and used the query history table/UI for this, this feature is more to make one's life easier.
I will have a look at the run_result file!

**Comment by robscriva** [comment]
Just wanting to chime in here as we leverage `query_tag` to do the reverse, ie tag the queries in Snowflake with some model info. Some info on what we're sticking in our `query_tag` here: https://github.com/dbt-labs/dbt-snowflake/issues/133

One of the challenges with the model <-> query_id relationship is that it's a one to many, ie incremental models generate multiple queries, ie a CTAS+MERGE. 

@jtcohen6 apologies for not searching for it, are both query_ids captured in that instance?
