### ISSUE TITLE
[CT-723] COPY INTO command not getting committed with dbt (on Snowflake)

### ISSUE THREAD

**Issue by bukosabino** [dbt-labs/dbt-snowflake#169]
### Describe the bug
I try to unload data from Snowflake to S3 using dbt.

`dbt run-operation unload_data_to_s3`

```
{% macro unload_data_to_s3() %}

    {{ log("Unloading data", True) }}
    COPY INTO <my_path_stage>
    FROM <my_table>
    FILE_FORMAT = (TYPE=CSV COMPRESSION=NONE)
    SINGLE=TRUE
    {{ log("Unloaded data", True) }}

{% endmacro %}
```

There are no errors on the log using dbt, but the file is not uploaded. However, everything works fine if I run the `copy into` command on the Snowflake CLI.

Things that I have tried:

- `ALTER SESSION SET AUTOCOMMIT=TRUE`
- `ALTER USER {{ target.user }} SET AUTOCOMMIT=TRUE`
- wrapping the copy into command with BEGIN; and COMMIT;

Am I missing something?

### Steps To Reproduce

You can use my macro on any table and defined stage.

### Expected behavior
Unload a new CSV file on my s3 bucket.

### System information
**The output of `dbt --version`:**
```
installed version: 0.21.0
   latest version: 1.0.0

Plugins:
  - snowflake: 0.21.0
  - postgres: 0.21.0
  - redshift: 0.21.0
  - bigquery: 0.21.0

```

**The operating system you're using:**
MAC

**The output of `python --version`:**
Python 3.7.13

### Additional context

The inverse pattern (load data from s3 to Snowflake) works as expected using this tool: https://github.com/dbt-labs/dbt-external-tables

**Comment by bukosabino** [comment]
I have solved wrapping the copy into command with:

```
{% call statement('unload_test', fetch_result=true, auto_begin=true) %}
...
{% endcall %}
```

**Comment by jtcohen6** [comment]
@bukosabino Glad you were able to solve this with `auto_begin=True`! I think you would also be able to solve it by wrapping your DML in explicit `begin;` + `commit`; statements:
```
{% macro unload_data_to_s3() %}

    {{ log("Unloading data", True) }}
    BEGIN;
    COPY INTO <my_path_stage>
    FROM <my_table>
    FILE_FORMAT = (TYPE=CSV COMPRESSION=NONE)
    SINGLE=TRUE;
    COMMIT;
    {{ log("Unloaded data", True) }}

{% endmacro %}
```

We made dbt do this for its DML statements during materialization, following Snowflake's recommendation last year. There's even A Macro For That:

https://github.com/dbt-labs/dbt-snowflake/blob/0829bd362568cb4003c05f4cd9f6a7dfd90cc5a6/dbt/include/snowflake/macros/adapters.sql#L262-L276

**Comment by bukosabino** [comment]
Hi @jtcohen6 ,

I tried using the options that you proposed and some others based on [this issue](https://github.com/dbt-labs/dbt-external-tables/issues/43):

- ALTER SESSION SET AUTOCOMMIT=TRUE
- ALTER USER {{ target.user }} SET AUTOCOMMIT=TRUE
- wrapping the copy into command with `BEGIN;` and `COMMIT;`

But, it never worked, `call statement` was the solution because I wanted to run from `run-operation`.

Thanks anyway!

And congrats on this fantastic project!
