### ISSUE TITLE
Snowflake Persist Docs (Materialization == Views, column level descriptions)

### ISSUE THREAD

**Issue by kevnoo** [dbt-labs/dbt-snowflake#17]
### Describe the feature
Given the database adapter is Snowflake, materialization type is View and persist docs is set true - create the view using the following snowflake syntax so that column descriptions from dbt schema.yml files are include:

CREATE OR REPLACE VIEW <VIEWNAME> (COL1 COMMENT 'COMMENT', COLN COMMENT 'COMMENT') AS SELECT COL1, COLN FROM TABLE;

### Describe alternatives you've considered
I am looking into submitting a PR myself but would benefit from oversight. We have also considered contacting Snowflake to include alter capabilities for columns within a view but believe this to be another alternative.

### Additional context
Snowflake 

### Who will this benefit?
All users of Snowflake who heavily rely on views and would like to use persist docs to capture doc details within the database itself for external dependencies

### Are you interested in contributing this feature?
Yes - more than happy to help - just require a push in the right direction

**Comment by spencer-taylor-workrise** [comment]
@jtcohen6 Opened PR #53 to resolve this (not sure if it notifies you when I tag the PR to this issue, my open source github chops are a little rusty 😅 )!
