### ISSUE TITLE
[CT-724] Bump cryptography upper bound limit

### ISSUE THREAD

**Issue by hhobson** [dbt-labs/dbt-snowflake#170]
### Describe the feature

`cryptography` package now has seven releases > 4 and it would be good to increase the upper bound limit for a couple of reasons:

- Newer versions will have fixes and potentially security updates
- Avoid dependency conflicts with packages using more up to date versions

Increasing upper bound limit to `<37.0.0` will bring it in line with upper bound limit for latest version (2.7.8) of `snowflake-connector-python`.

### Additional context
Please include any other relevant context here.

### Who will this benefit?
What kind of use case will this feature be useful for? Please be specific and provide examples, this will help us prioritize properly.

Users looking to install dbt & recent version of Airflow using Airflow's constraints file or any package that is using more up to date version of cryptography

### Are you interested in contributing this feature?
Let us know if you want to write some code, and how we can help.

Raising issue so I can raise PR

**Comment by jtcohen6** [comment]
Thanks @hhobson!

> Increasing upper bound limit to `<37.0.0` will bring it in line with upper bound limit for latest version (2.7.8) of `snowflake-connector-python`.

Agree that this is exactly the thing we should be doing.

For some reason, `dependabot` is not catching dependencies defined in `setup.py`. We might have some logic in there that's incompatible, and prevents it from opening automated PRs. In the meantime, I'm very grateful!
