### ISSUE TITLE
[CT-755] pip dependency resolver ERROR

### ISSUE THREAD

**Issue by ValconFloris** [dbt-labs/dbt-snowflake#176]
### Describe the bug
Hi all, 
I've got an issue with installing dbt-snowflake and working with it, or even seeing it. 
After I installed dbt-snowflake (even with a 'pip3 install --upgrade --force-reinstall dbt-snowflake') I get an error (shown below) "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed......" I first thought it didn't matter as I do not need these, but doing a 'dbt --version' command gives me another error 'failed to create process'. 

Is there anyone familar with this and knows what goes wrong here? 

My python version is 3.9
```


### Additional context
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dbt-redshift 0.21.0 requires dbt-postgres==0.21.0, which is not installed.
dbt-redshift 0.21.0 requires dbt-core==0.21.0, but you have dbt-core 1.1.1 which is incompatible.
dbt-bigquery 0.21.0 requires dbt-core==0.21.0, but you have dbt-core 1.1.1 which is incompatible.

Successfully installed Babel-2.10.3 Jinja2-2.11.3 MarkupSafe-2.0.1 agate-1.6.3 asn1crypto-1.5.1 attrs-21.4.0 certifi-2022.6.15 cffi-1.15.0 charset-normalizer-2.0.12 click-8.1.3 colorama-0.4.4 cryptography-3.4.8 dbt-core-1.1.1 dbt-extractor-0.4.1 dbt-snowflake-1.1.0 future-0.18.2 hologram-0.0.15 idna-3.3 importlib-metadata-4.11.4 isodate-0.6.1 jsonschema-3.2.0 keyring-23.6.0 leather-0.3.4 logbook-1.5.3 mashumaro-2.9 minimal-snowplow-tracker-0.0.2 msgpack-1.0.4 networkx-2.8.3 oscrypto-1.3.0 packaging-21.3 parsedatetime-2.4 pyOpenSSL-21.0.0 pycparser-2.21 pycryptodomex-3.14.1 pyjwt-2.4.0 pyparsing-3.0.9 pyrsistent-0.18.1 python-dateutil-2.8.2 python-slugify-6.1.2 pytimeparse-1.1.8 pytz-2022.1 pywin32-ctypes-0.2.0 pyyaml-6.0 requests-2.28.0 setuptools-62.4.0 six-1.16.0 snowflake-connector-python-2.7.8 sqlparse-0.4.2 text-unidecode-1.3 typing-extensions-4.2.0 urllib3-1.26.9 werkzeug-2.1.2 zipp-3.8.0

**Comment by ValconFloris** [comment]
Thanks, that was a quick fix. I still don't understand how dbt-redshift and dbt-bigquery were installed in the first place though. But this helps. Could you also explain me why, when I run 'dbt --version' I get a 'failed to create process'? 

Seems strange as with the pip3 freeze I do see the dbt-core installed as well as the dbt-snowflake

**Comment by jtcohen6** [comment]
> when I run 'dbt --version' I get a 'failed to create process'?

About this, I'm not sure! It sounds like an error with your Python / pip environment, [maybe](https://stackoverflow.com/questions/17373265/pip-easy-install-failure-failed-to-create-process)?

**Comment by ValconFloris** [comment]
I figured it out. It was still referring to a recent upgrade of Python 3.10 (which I thought I de-installed) I am using 3.9. After removing the folders an content of 3.10 it worked fine as it was doing everything with 3.9
