### ISSUE TITLE
[CT-795] Request #5327 for dbt-snowflake to align with dbt-core

### ISSUE THREAD

**Issue by DetailsDevil** [dbt-labs/dbt-snowflake#184]
### Describe the feature
Red/green colouring is no longer visible in dbt-snowflake v1.1 on Windows, identical issue as [#5327](https://github.com/dbt-labs/dbt-core/pull/5327) for dbt-core .
Instead we see unexpected characters such as [←[32mPASS←[0m in 0.82s] 

### Describe alternatives you've considered
I refer to [#5327](https://github.com/dbt-labs/dbt-core/pull/5327)

### Additional context
It would ideal that other adapters are updated similarly as dbt-core.

### Who will this benefit?
Users of dbt adapters - in addition to users of dbt-core

### Are you interested in contributing this feature?
Not at this time, I believe the work as been done.

**Comment by jtcohen6** [comment]
Hey @DetailsDevil, I don't believe there's any change needed in this codebase to get the fix — just a matter of upgrading to the latest `dbt-core`.

Have you tried using `dbt-snowflake==1.1.0` together with `dbt-core==1.1.1`? If you install dbt via `pip`, that should be easy. If you install via Homebrew, we just updated the formula yesterday (https://github.com/dbt-labs/homebrew-dbt/pull/140).

**Comment by rloredo** [comment]
I have the same problem with logs that I get in Airflow, see here https://github.com/dbt-labs/dbt-snowflake/issues/250 
I'm using the latest dbt-snowflake docker image, that doesn't have the 1.2.1 core update...

**Comment by jtcohen6** [comment]
@rloredo It sounds like the resolution to https://github.com/dbt-labs/dbt-snowflake/issues/250 was to use the global config that disables color output, which is supported.

I'm going to close this issue in the meantime.
