### ISSUE TITLE
[CT-835] file reformat as part of ergo mats grants work

### ISSUE THREAD

**Issue by McKnight-42** [dbt-labs/dbt-snowflake#193]
### Describe the feature
align file structure to be more similar to core for housing of overridden macros instead of storing them all in adapters.sql

### Who will this benefit?
adapter maintainers, contributors who want to keep like work in sectioned areas

### Are you interested in contributing this feature?
yes

**Comment by Fleid** [comment]
Hey @McKnight-42 is this still a thing?
