### ISSUE TITLE
Allow query_tag configuration in snapshot model for Snowflake

### ISSUE THREAD

**Issue by ErikDataDesigner** [dbt-labs/dbt-snowflake#20]
### Describe the feature
When using Snowflake allow the snapshot config to accept and honor the query_tag parameter.

### Additional context
This enhancement is specific for snowflake implementations

### Who will this benefit?
Snapshots can be end up being compute intensive, this enhancement would provide a more simplified way for db administrators to collect the data required to monitor and manage the cost. 

### Example

{% snapshot snapshot_name %}

{{
    config(
      target_database='db',
      target_schema='snapshots',
      unique_key='id',
      strategy='check',
      check_cols=['col_a'],
      **query_tag='SNAPSHOT'**      
    )
}}

select * from {{ source('db', 'table') }}

{% endsnapshot %}

**Comment by anthu** [comment]
How about wrapping the standard behaviour of the materialisation? Like:

```
{% materialization snapshot, adapter='snowflake' %}
    {% set original_query_tag = set_query_tag() %}
        {% set relations = materialization_snapshot_default() %}
    {% do unset_query_tag(original_query_tag) %}

    {{ return(relations) }}
{% endmaterialization %}
```
And 
```
{% materialization seed, adapter='snowflake' %}
    {% set original_query_tag = set_query_tag() %}
        {% set relations = materialization_seed_default() %}
    {% do unset_query_tag(original_query_tag) %}
    
    {{ return(relations) }}
{% endmaterialization %}
```
This do work just fine as a project-scoped materialisation. 

I would gladly open a PR for this. But I'm struggling to get my head around the Contributions Guide for dbt adapters. The one linked it this repo seems to be out of date (but that might be worth discussed in a separate issue ;) )

**Comment by jtcohen6** [comment]
@anthu Glad to hear that works locally. It's a pretty elegant way to support query tags for seeds + snapshots on Snowflake, without requiring a ton of duplicated code. I'd be open to a PR for it.

We do need new contributing guides for the adapter repos. For the time being, you can get started by:
- forking/cloning this repo
- in a virtualenv: `pip install -e . -r dev_requirements.txt` (will install latest changes from `dbt-core` as well)
- making changes to the code inside `dbt/`
- running dbt from that virtualenv

**Comment by anthu** [comment]
Thanks for the prompt reply. 

I got it to run meanwhile - the tricky part is definitely setting up the Snowflake connection for the test to run - it simply refused to pick them up:

this worked `python3 -m pytest -m profile_snowflake` instead simply running ~pytest~.

I will make it ready later - what are your thought on this being more or less an "internal" method?

**Comment by jtcohen6** [comment]
You're right, this is an "internal" method, and there's no guarantee that materializations will always work this way (creating a macro named `materialization_<name>` behind the scenes).

Given that dbt Labs maintains this adapter, I feel more comfortable with it. In fact, I think it will be a good check if we ever change this behavior. It isn't exactly documented, so it isn't exactly contracted in v1—but we can fairly assume that there are users who have observed this capability, and now projects which rely on it.
