### ISSUE TITLE
[CT-935] Adapter-specific configs not supported by Python models

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-snowflake#214]
## Describe the feature
These are configurations that are applied within the [`create table as`](https://github.com/dbt-labs/dbt-snowflake/blob/c0b9274d24ec937d13cea796767c5225c65d48cd/dbt/include/snowflake/macros/adapters.sql#L3) statement in Snowflake:
`transient`
`cluster_by`
`copy_grants + automatic_clustering`

Right now in python models we are just [saving everything with default settings](https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/include/snowflake/macros/materializations/table.sql#L52). We should reach parity for this for python models where possible and raise a clear error when running with options that is not supported. This probably involves having [`py_write_table`](https://github.com/dbt-labs/dbt-snowflake/blob/c0b9274d24ec937d13cea796767c5225c65d48cd/dbt/include/snowflake/macros/materializations/table.sql#L41) take in those parameters and generate the correct python code

## Motivation:
User would be able to optimize the storage format based on their usage of the table.

## Acceptance criteria
Python model would materialize the table with the correct option, and raise error when unsupported option is being specified.

## Tests for the PR
You should add integration tests to run the table materialization with supported options, then check that the table has intended property, for example [this](https://community.snowflake.com/s/question/0D50Z00008GTHmhSAH/how-can-i-get-the-number-of-micro-partitions-in-a-table) might be a way to check partitions. You should also add tests to to make sure we raised the error on unsupported options.

**Comment by jtcohen6** [comment]
These are configurations that are applied _within_ the `create table as` statement in Snowflake:
- `transient`
- `cluster_by`
- `copy_grants` + `automatic_clustering`

**Comment by iknox-fa** [comment]
Estimations in JIRA reflect assumption that all table options are available when creating tables in Snowpark.
