### ISSUE TITLE
[CT-936] Snowflake-connector-python typing_extensions version is incompatible 

### ISSUE THREAD

**Issue by leoch20** [dbt-labs/dbt-snowflake#215]
### Describe the bug
We are getting this error:
`ImportError: cannot import name 'NamedTuple' from 'typing_extensions'`
This comes from from [snowflake-connector-python](https://github.com/snowflakedb/snowflake-connector-python).
The recommendation here https://github.com/snowflakedb/snowflake-connector-python/issues/1206#issuecomment-1194884607 is to upgrade `typing-extensions>=4.3.0`. However, dbt-core depends on typing-extensions<3.11.

### Steps To Reproduce
Install `dbt-snowflake==1.0.0` and try to build a project

### Expected behavior
It should run dbt

### Screenshots and log output
![Screenshot 2022-07-26 at 11 41 59](https://user-images.githubusercontent.com/29922536/180976219-19808ae1-d710-4e18-8df7-978baef577dc.png)

**The operating system you're using:**
Docker python:3.7.10-slim

**Comment by yathorOo** [comment]
We set the snowflake-connector-python to 2.7.9 for the time being and that fixed the issue.
`snowflake-connector-python==2.7.9
dbt-snowflake==1.0.0`

**Comment by leoch20** [comment]
Thanks @yathorOo that did it for us.
We tried upgrading dbt-snowflake to 1.1.0 on MWAA but that created other issues.
However, the issue still persists with the stand-alone dbt-snowflake installation.

**Comment by LucasRBarbosa-wex** [comment]
Thanks for the help @yathorOo - we have been running over the same issues since last night during some of our process.

**Comment by jtcohen6** [comment]
> We tried upgrading dbt-snowflake to 1.1.0 on MWAA but that created other issues.

@leoch20 Curious to hear what those other issues were? Related to dependency conflicts? This is what I was going to recommend, since we loosened the `typing-extensions` upper bound in dbt-core v1.1+

**Comment by patricktrainer** [comment]
This popped up on my team today as well. 

Running: 
- docker python 3.8
- dbt-snowflake 1.0.8

Bumping to python 3.9 resolved the issue for us.
