### ISSUE TITLE
[CT-973] [Feature] Support view materialization for python model

### ISSUE THREAD

**Issue by ChenyuLInx** [dbt-labs/dbt-snowflake#220]
### Describe the feature
Snowflake dataframe operations actually compile down to sql when it is executing, this created a unique functionality to express logic in snowflake dataframe operation then create a view out of that logic, see [create_or_replace_view](https://docs.snowflake.com/en/developer-guide/snowpark/reference/python/_autosummary/snowflake.snowpark.html#snowflake.snowpark.DataFrame.create_or_replace_view), [overview of snowpark](https://quickstarts.snowflake.com/guide/getting_started_with_snowpark_python/index.html?index=..%2F..index#0). 

With this function, python model in snowflake can be materialized as view sometimes(if all of the logics are snowpark dataframe transformation, maybe something else?). We should support this in dbt-snowflake

Outcome:
Python model that only have snowpark dataframe transformation logic can be materialized as view, and being used by downstream dbt models

**Comment by lostmygithubaccount** [comment]
can this feasibly be supported for all adapters? if so, we should also open a general issue. my impression is this will be most straightforward on Snowflake

given my current understanding, going to classify this as a spike with acceptance criteria:

- understand technical feasibility of supporting view materialization for Snowflake (and ideally other adapters)
- rough outline of future work needed to support
