### ISSUE TITLE
[CT-1039] Snowflake: Configuration of virtuell warehouses for tests

### ISSUE THREAD

**Issue by Kratzbaum92** [dbt-labs/dbt-snowflake#233]
### Describe the feature
Extend the configuration of virtuell warehouses to tests.
https://docs.getdbt.com/reference/resource-configs/snowflake-configs#configuring-virtual-warehouses

ATM it's only possible to configure an explicit warehouse to explicit models.
In a scenario with many small models + 2-3 big models (data volume/ runtime) you would probably go to environmental config like this:

environment: PRODUCTION
warehouse: SMALL

+ virtuell warehouse ( for big models ): XL

Problem: It's not possible to influence the runtime of tests on your big model without changing the standard warehouse, which would potentially lead to a massive cost increase.

### Describe alternatives you've considered
It would be possible to write tests as models and to test against these.

Problem: unnecessary models in repo and lineage

### Additional context
Please include any other relevant context here.

### Who will this benefit?
Cost sensitive customers.

### Are you interested in contributing this feature?
Let us know if you want to write some code, and how we can help.

**Comment by Fleid** [comment]
Hi @Kratzbaum92, this sounds similar to issue #23 .
Can you confirm this is indeed the case? Thanks!

**Comment by Kratzbaum92** [comment]
> Hi @Kratzbaum92, this sounds similar to issue #23 .
> Can you confirm this is indeed the case? Thanks!

Yes, It's the same topic.

**Comment by jtcohen6** [comment]
Thanks for the confirmation! Let's close in favor of that other issue. I just left a comment laying out what I see as the next steps there.
