### ISSUE TITLE
[CT-1066] [CT-1065] snowflake alter_column_type feature extension to support collate at schema level

### ISSUE THREAD

**Issue by abhishek2908478** [dbt-labs/dbt-snowflake#240]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Sometimes we have collate for tables in snowflake at the schema level and not at the file level. So if there is any change in the datatype of a particular column of a table and if I try to use persistent materialization to change it in snowflake  then it gives an error saying that there is some collate difference at the schema level and at file level because of which the process fails. I will urge you to please add functionality to check collate of the table present in snowflake and add it to the alter statement after fetching it.

**Comment by abhishek2908478** [comment]
**Query will help you to get the collate name** 
select collate_name from information_schema.columns where table_name = table
and table_schema = schema

**Query to alter column with collate at schema level**
alter table table_name alter column_name  set data type varchar(500) collate  collate_name

**Comment by jtcohen6** [comment]
Oof, okay - tricky if this requires an additional (introspective) query. This might want to be a new user-supplied configuration (at the column level? table/schema level?). Though it looks like it's not possible to add collation after a table has been created ([docs](https://docs.snowflake.com/en/sql-reference/sql/alter-table.html#:~:text=Setting%20the%20parameter%20does%20not%20change%20the%20collation%20specification%20for%20any%20existing%20columns.))...

**Comment by abhishek2908478** [comment]
This additional code is required only when collate is present at schema level. If the collate will be present at file level then no issues, the code we have currently will work.
What you have to do is create two if conditions, one where  collate is present at file level. There you can just call the adapter which currently is there. In the else part you have to check if the collate is present at schema level by querying the information_schema.columns table and then if it is null you can pass the same adapter else the collate value what you get will be put in the alter query

**Comment by abhishek2908478** [comment]
Any updates on this ?
