### ISSUE TITLE
[CT-1188] [Feature] Support Migration from Transient to Permanent Table Configurations

### ISSUE THREAD

**Issue by ernestoongaro** [dbt-labs/dbt-snowflake#262]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Changing transient=true on a table that was built with transient=false has no effect, particularly for "long lived tables" like snapshots, this is a problem.

### Describe alternatives you've considered

https://stackoverflow.com/questions/73469697/snowflake-transient-to-permanent-table

**Comment by jtcohen6** [comment]
Added context from Slack thread: rather than needing to switch this partway through a table's existence, the right answer here might be **better defaults**!

> Makes sense to me that snapshots would want to be permanent tables (support `undrop` + time-travel for >1 day).
> We could also consider
- updating [the docs here](https://docs.getdbt.com/reference/resource-configs/snowflake-configs#transient-tables) to recommend setting transient: false for all snapshots
- (code change) setting `transient = false` for snapshots by default

**Comment by dbeatty10** [comment]
+1 for better defaults by making the code change to set `transient = false` for snapshots by default -- feels like we could easily make that change whether or not we take up supporting migration from transient to permanent.

**Comment by dbeatty10** [comment]
> * updating [the docs here](https://docs.getdbt.com/reference/resource-configs/snowflake-configs#transient-tables) to recommend setting transient: false for all snapshots
> * (code change) setting `transient = false` for snapshots by default

Capture these in a new issue: https://github.com/dbt-labs/dbt-snowflake/issues/332
