### ISSUE TITLE
[CT-1254] [Bug] Unable to install via pip on Ubuntu

### ISSUE THREAD

**Issue by cverhoef** [dbt-labs/dbt-snowflake#278]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Following the steps on this page to install dbt-snowflake on Ubuntu does not work as of 26 September: https://docs.getdbt.com/dbt-cli/install/pip. It returns errors when installing the dependencies when executing the command `pip install dbt-snowflake`.

The errors relate to deprecations caused by the release 22.1.0 of the module pyOpenSSL.

This happens for dbt-snowflake version 1.0.0 and for subsequent versions.

### Expected Behavior

A newer version of pyOpenSSL was released (22.1.0), which has breaking changes. Because snowflake-connector-python is requiring a version <23.0.0 this update is used now. I would expect that the requirement is 22.0.0 to not install the version containing the breaking changes or that the deprecated functions are not being used.

### Steps To Reproduce

- Run the following command according to the dbt documentation on an Ubuntu machine to install Python and other dependencies:
```
sudo apt-get install git libpq-dev python-dev python3-pip
sudo apt-get remove python-cffi
sudo pip install --upgrade cffi
pip install cryptography~=3.4
```
- Next install dbt-snowflake=1.1.0 (or another version)
```
python3 -m venv dbt-env
source dbt-env/bin/activate
pip install dbt-core==1.1.0
pip install dbt-snowflake==1.1.0
```

This should reproduce the failing installation. 

### Relevant log output

```shell
File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
  File "/home/vsts/work/1/s/dbt-env/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/home/vsts/work/1/s/dbt-env/lib/python3.8/site-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/home/vsts/work/1/s/dbt-env/lib/python3.8/site-packages/OpenSSL/crypto.py", line 3224, in <module>
    utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument 'name'
```

### Environment

```markdown
- OS: Ubuntu 20.04
- Python: 3.8.10
- dbt-core: 1.1.0
- dbt-snowflake: 1.1.0
```

### Additional Context

Workaround is available:
Run `pip install pyOpenSSL==22.0.0` before running `pip install dbt-core==1.1.0`.

**Comment by r-moctezuma** [comment]
Confirming that this is impacting other adapters such as `dbt-redshift` as well, and that the workaround addresses them.

Thank you for posting this, @cverhoef !

**Comment by jtcohen6** [comment]
Thanks for posting @cverhoef, and sorry for the delay following up!

Am I right in thinking that this is really an issue in `snowflake-connector-python`, since that's where [the `pyOpenSSL` requirement](https://github.com/snowflakedb/snowflake-connector-python/blob/main/setup.cfg#L49) is defined, and where the deprecated methods are being called?

@r-moctezuma I'm less sure why this would be cropping up in `dbt-redshift` as well. It doesn't look like `pyOpenSSL` is a dependency of `boto3`, or of `dbt-core`. Could you include the stacktrace of the error you've been seeing?

**Comment by cverhoef** [comment]
> Am I right in thinking that this is really an issue in snowflake-connector-python, since that's where [the pyOpenSSL requirement](https://github.com/snowflakedb/snowflake-connector-python/blob/main/setup.cfg#L49) is defined, and where the deprecated methods are being called?
That seems to be indeed the case.

**Comment by Fleid** [comment]
Closing as this is not on our side. Please comment below if need be and I'll open it again.
