### ISSUE TITLE
[CT-1620] Unhandled error while executing test - 252005: Failed to convert current row, cause: [Snowflake Exception] unknown arrow internal data type(252732072) for FIXED data

### ISSUE THREAD

**Issue by AnandaRoc360** [dbt-labs/dbt-snowflake#288]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I tried running some dbt generic tests (unique, not_null, ..etc) for dbt-snowflake. I got the below errors

Unhandled error while executing test
252005: Failed to convert current row, cause: [Snowflake Exception] unknown arrow internal data type(252732072) for FIXED data

### Expected Behavior

The generic tests should pass without any internal/abnormal errors.

### Steps To Reproduce

1) dbt test -s (model_name)

### Relevant log output

```shell
1 of 2 START test not_null_(model details) ....................... [RUN]
Unhandled error while executing test.(project name).not_null_(model details).4160c5e7fe 
252005: Failed to convert current row, cause: [Snowflake Exception] unknown arrow internal data type(160100344) for      FIXED data

2 of 2 START test unique_(model details) ......................... [RUN]
03:31:21  Unhandled error while executing test.(project name).unique_(model details).9b30087e69
252005: Failed to convert current row, cause: [Snowflake Exception] unknown arrow internal data type(160100344) for FIXED data
```

### Environment

```markdown
dbt-core       1.2.1
dbt-snowflake  1.2.0
snowflake-connector-python   2.7.8
Python 3.9.12
```

**Comment by sfc-gh-ripu** [comment]
Hi, this may or may not be related to a non-documented behavior change from a snowflake release last week, where processes relying on `desc table` or `get ddl` statements are potentially impacted. We are actively working on rolling back this change this week. I suggest working with snowflake support to get this looked into.

**Comment by nathaniel-may** [comment]
Hi @AnandaRoc360, thanks for logging this ticket with us. We looked into it this morning and as @sfc-gh-ripu has added in his comment, we believe this will be resolved on Snowflake's end. If their fix later this week doesn't solve your problem please feel free to reopen this ticket.

**Comment by AnandaRoc360** [comment]
Re-opening this case

**Comment by JonCrawford** [comment]
FYI, uninstalling pyarrow altogether fixed this for me. Attempting to upgrade or reinstall pyarrow makes the issue return.

**Comment by HFPaulRomieu** [comment]
Hi, I have the same issue: InterfaceError: 252005: 252005: Failed to convert current row, cause: [Snowflake Exception] unknown arrow internal data type(44638120) for FIXED data

**Comment by alphairys** [comment]
I've run into the same issue today, when running snowflake-python-connector 2.8.1:

InterfaceError: 252005: 252005: Failed to convert current row, cause: [Snowflake Exception] unknown arrow internal data type(38226584) for FIXED data

**Comment by hannahg141** [comment]
> I've run into the same issue today, when running snowflake-python-connector 2.8.1:
> 
> InterfaceError: 252005: 252005: Failed to convert current row, cause: [Snowflake Exception] unknown arrow internal data type(38226584) for FIXED data

Me too, 

snowflake-connector-python 2.9.0
python 3.9.16
pyarrow 10.0.1 (tried uninstall and reinstall with no luck)

**Comment by csetzkorn** [comment]
Me too ...

**Comment by tmannen** [comment]
For me this seems to happen only on MacOS but not Linux. Versions:

dbt-snowflake==1.4.1
dbt-core==1.4.5
