### ISSUE TITLE
[CT-1430] [Bug] GitHub Actions: Deprecating save-state and set-output commands

### ISSUE THREAD

**Issue by kevinneville** [dbt-labs/dbt-snowflake#302]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

GitHub Actions: Deprecating save-state and set-output commands, these should be replaced with the proposed solution.
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.

### Expected Behavior

We should not see the warnings.

### Steps To Reproduce

Warnings present in checks.

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-snowflake:
```

**Comment by McKnight-42** [comment]
closing due to being covered by #520
