### ISSUE TITLE
[CT-1458] [Feature] change default dbt-py method to anonymous stored procedures (sprocs)

### ISSUE THREAD

**Issue by lostmygithubaccount** [dbt-labs/dbt-snowflake#305]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

change to anonymous sprocs as the default

the code is already there, the default should just be changed once it's ready per Snowflake team

should keep stored sprocs as an option

### Describe alternatives you've considered

n/a

### Who will this benefit?

all dbt-py users on Snowflake with slightly faster execution

### Are you interested in contributing this feature?

no

**Comment by jtcohen6** [comment]
Anon sprocs are now available to everyone with access to Snowpark (Open Preview), so we can do this any time: https://docs.snowflake.com/en/sql-reference/sql/call-with.html

**Comment by jtcohen6** [comment]
@Fleid @nathaniel-may What do you think of prioritizing this for inclusion in `dbt-snowflake==1.4.0`?
