### ISSUE TITLE
[CT1490] Convert test_snowflake_view_dependency

### ISSUE THREAD

**Issue by McKnight-42** [dbt-labs/dbt-snowflake#320]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

convert integration test to functional test

**Comment by Fleid** [comment]
Closing as the PR was merged
