### ISSUE TITLE
[CT-1522] [Bug] Easy : Can't Create lowercase model on SnowFlake (double quotes conflict)

### ISSUE THREAD

**Issue by jugodfroy** [dbt-labs/dbt-snowflake#330]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When trying to create a python model with lowercase name, the name of the model is under double quotes which lead to a conflit of double quote in the function save_as_table().

![image](https://user-images.githubusercontent.com/79590825/202451775-681be1e0-8d03-4082-8c94-1229c88dde52.png)

### Expected Behavior

The expected behavior is the good creation of the model in lowercase in Snowflake

### Steps To Reproduce

In dbt_project.yml specifiy the quoting settings :
![image](https://user-images.githubusercontent.com/79590825/202453245-6479798b-a373-4565-ae76-b546252d36a7.png)

Then try to run a python model. The error should be reproduced.

### Relevant log output

```shell
![image](https://user-images.githubusercontent.com/79590825/202451775-681be1e0-8d03-4082-8c94-1229c88dde52.png)
```

### Environment

```markdown
- OS:Windows 10
- Python:
- dbt-core:1.3.0
- dbt-snowflake:

Ran with a Job
```

### Additional Context

Idea To fix : in file : dbt-snowflake/dbt/include/snowflake/macros/materializations/table.sql

line 52 (double to simple quote) : 
replace `df.write.mode("overwrite").save_as_table("{{ target_relation }}", create_temp_table={{temporary}})`
by `df.write.mode("overwrite").save_as_table('{{ target_relation }}', create_temp_table={{temporary}})`

**Comment by jtcohen6** [comment]
@jugodfroy Thanks for opening - I think you've got the right idea!

> line 52 (double to simple quote)

This is definitely the most expedient. For consistency in output code, we might prefer to keep it as a double-quoted string, with escapes for any quotes inside. This looks awkward, but something like it might get the job done:
```python
target_relation = {{ target_relation }}
df.write.mode("overwrite").save_as_table("{{ target_relation | replace('"', '\"' }}", create_temp_table={{temporary}})
```

**Comment by jtcohen6** [comment]
Let's go for the escape route... just in case the quoted relation name contains a single quote (gross)

@jugodfroy Is this something you'd be interested in contributing?

**Comment by jugodfroy** [comment]
I would love to !
Tell me how can I contribute @jtcohen6

**Comment by jtcohen6** [comment]
@jugodfroy Check out [the contributing guide](https://github.com/dbt-labs/dbt-snowflake/blob/main/CONTRIBUTING.MD)!

We'll just want an additional test case [here](https://github.com/dbt-labs/dbt-snowflake/blob/main/tests/functional/adapter/test_python_model.py), which has a Python model with a lowercase name + `quoting` config enabled.

**Comment by jugodfroy** [comment]
Actually it will be quicker if someone else fix this one :)
