### ISSUE TITLE
[CT-1529] [Feature] Support Python 3.11

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-snowflake#331]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Main issue:
https://github.com/dbt-labs/dbt-core/issues/6147

**Comment by Dikootje** [comment]
FYI: Seems to depend on package python-snowflake-connector upgrade to support 3.11:
https://github.com/snowflakedb/snowflake-connector-python/issues/1289
https://github.com/snowflakedb/snowflake-connector-python/issues/1345

**Comment by dataders** [comment]
FYI @dbt-labs/core-adapters, `snowflake-connector-python==3.0.0` is now live ([PyPI](https://pypi.org/project/snowflake-connector-python/3.0.0/) | [GitHub](https://github.com/snowflakedb/snowflake-connector-python/releases/tag/v3.0.0))!

**Comment by axelwaserman** [comment]
Any updates on this please ?

**Comment by mikealfare** [comment]
It's currently in review to be put into the 1.5 beta. It's stuck behind this ticket: https://github.com/dbt-labs/dbt-snowflake/pull/476, though we expect little work once that is approved. @Fleid can speak more to the timing.
