### ISSUE TITLE
[CT-1538] [Feature] Default snapshots to `transient = false`

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-snowflake#332]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

By default, set `transient = false` for snapshots.

This was described by @jtcohen6 [here](https://github.com/dbt-labs/dbt-snowflake/issues/262#issuecomment-1248084144):

> * (code change) setting `transient = false` for snapshots by default

and

> * updating [the docs here](https://docs.getdbt.com/reference/resource-configs/snowflake-configs#transient-tables) to recommend setting transient: false for all snapshots

**Comment by ronmorgen1** [comment]
I'll be glad to pick this up

**Comment by dbeatty10** [comment]
Awesome @ronmorgen1 !
