### ISSUE TITLE
[CT-1597] [Bug] Makefile and Contributing instructions are different

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-snowflake#340]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The `CONTRIBUTING.MD` file mentions running `pip install -e . -r dev-requirements.txt` to setup the dev environment (which works), but the the Makefile for the `dev` entry mentions running `pip install -r dev-requirements.txt && pre-commit install` (which doesn't install `dbt-snowflake`)

### Expected Behavior

I would expect `make dev` to run the command required to start developing, e.g. the one from `CONTRIBUTING.MD`

### Steps To Reproduce

- clone the repo
- do a `make dev`

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-snowflake:
```

**Comment by jtcohen6** [comment]
@b-per Thanks for opening! This should be a one-liner, for anyone who wants it :)
