### ISSUE TITLE
[CT-1667] [Bug] Vulnerability on cryptography dependency

### ISSUE THREAD

**Issue by Surbias** [dbt-labs/dbt-snowflake#359]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

As of yesterday, Snyk has reported on a vulnerability for the cryptography package here: https://security.snyk.io/vuln/SNYK-PYTHON-CRYPTOGRAPHY-3172287

However `dbt-snowflake` is locking the package:

```
cryptography>=3.2,<37.0.0"
``` 

Would it be possible to update this package in `dbt-snowflake`?

### Expected Behavior

I expect the package to be updated as to not expose this vulnerability issue.

### Steps To Reproduce

Using the [snyk-cli](https://docs.snyk.io/snyk-cli).

```sh
$ snyk test
```

### Relevant log output

```shell
Issues with no direct upgrade or patch:
  ✗ Denial of Service (DoS) [Medium Severity][https://security.snyk.io/vuln/SNYK-PYTHON-CRYPTOGRAPHY-3172287] in cryptography@36.0.2
    introduced by dbt-snowflake@1.3.0 > cryptography@36.0.2 and 2 other path(s)
  No upgrade or patch available
```

### Environment

```markdown
- OS: macOS Ventura 13.0.1
- Python: 3.0
- dbt-core: 1.3.1
- dbt-snowflake: 1.3.0
```

**Comment by dbeatty10** [comment]
Thanks for opening @Surbias !

I just opened https://github.com/dbt-labs/dbt-snowflake/pull/360 as a result. I don't think `cryptography` has published a new version yet that includes this fix, so this won't be completely resolved until then.

Thank you again for letting us know 🙌
