### ISSUE TITLE
[CT-1676] [Feature] Support constraints in Snowflake following the dbt Core implementation

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-snowflake#365]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Allow the definition of column constraints and data types for Snowflake tables, in the CTAs statement.

Linked to the dbt-core issues https://github.com/dbt-labs/dbt-core/issues/6079 and https://github.com/dbt-labs/dbt-core/issues/6271

### Who will this benefit?

People wanting to leverage the dbt Core column constraints capability when using dbt with Snowflake

### Are you interested in contributing this feature?

Yes

**Comment by dbeatty10** [comment]
@b-per I heard on the grapevine that you are planning to open a PR for this one, so I assigned it to you. Forgive me if I heard wrong!
