### ISSUE TITLE
[CT-1724] [Bug] Snowflake Account/Password Auth Failures Should Not Trigger A Retry

### ISSUE THREAD

**Issue by beauxparker** [dbt-labs/dbt-snowflake#373]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Currently on job runs if the environment's deployment credentials are incorrect, dbt will attempt to open a Snowflake connection 3 times, stating "Snowflake adapter: Got a retryable error when attempting to open a snowflake connection." This can lead to the user being temporarily locked out in Snowflake for the cooldown period, unless their system administrator takes action. 

### Expected Behavior

I think it would be ideal if the connection was not attempted more than once if the user's credentials are incorrect as to not lock the user out/

### Steps To Reproduce

1. In a deployment environment, update the deployment credentials to either have an incorrect Snowflake username or password.
2. Schedule or kick off a run with bad credentials.
3. Once the run fails you can see in the debug logs that dbt attempts to open the connection 3 times before the user is locked out.

### Relevant log output

```shell
Database Error2022-12-23 17:34:09.316913 (ThreadPoolExecutor-1_0): 17:34:09  Opening a new connection, currently in state init
2022-12-23 17:34:10.111064 (ThreadPoolExecutor-1_0): 17:34:10  Snowflake adapter: Got a retryable error when attempting to open a snowflake connection.
3 attempts remaining. Retrying in 30 seconds.
Error:
250001 (08001): Failed to connect to DB: {account}.snowflakecomputing.com: Incorrect username or password was specified.
2022-12-23 17:34:40.778304 (ThreadPoolExecutor-1_0): 17:34:40  Snowflake adapter: Got a retryable error when attempting to open a snowflake connection.
2 attempts remaining. Retrying in 30 seconds.
Error:
250001 (08001): Failed to connect to DB: {account}.snowflakecomputing.com: Incorrect username or password was specified.
2022-12-23 17:35:11.524513 (ThreadPoolExecutor-1_0): 17:35:11  Snowflake adapter: Got a retryable error when attempting to open a snowflake connection.
1 attempts remaining. Retrying in 30 seconds.
Error:
250001 (08001): Failed to connect to DB: {account}.snowflakecomputing.com:. Incorrect username or password was specified.
  250001 (08001): Failed to connect to DB: {account}.snowflakecomputing.com: User temporarily locked. Contact your local system administrator or please create a case with Snowflake Support or reach us on our support line:
```

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-snowflake:
```

**Comment by dbeatty10** [comment]
Thanks for opening @beauxparker !

It feels reasonable to expect to _not_ retry in the case of an "Incorrect username or password was specified" error. In fact, you make a compelling case why it is desireable to not retry.

Selfishly, I decided not to reproduce this -- I'm going to trust your log output on this one 😎 

### What I think is going on
[Here](https://github.com/dbt-labs/dbt-snowflake/blob/e18c501175c84d5b08d66244533e636a5a04dba1/dbt/adapters/snowflake/connections.py#L307-L330) is where I think the retry is happening in dbt-snowflake.

So it'd be a matter of determining which type of Snowflake error is being raised and then making sure it isn't in the `retryable_exceptions` list.

But I have a few unconfirmed suspicions:
- That "Incorrect username or password was specified" will correspond to HTTP response code 403.
- HTTP response code 403 corresponds to `FORBIDDEN` in `snowflake-connector-python`
- ❗`FORBIDDEN` corresponds to `OtherHTTPRetryableError` in `snowflake-connector-python` [[1]](https://github.com/snowflakedb/snowflake-connector-python/blob/adb34d69a2c2819b6ea31e58558093ccc0450626/src/snowflake/connector/network.py#L177-L191
)

If that's all true, then that means snowflake-connector-python is bundling all these different errors into `OtherHTTPRetryableError`:
```
        BAD_REQUEST,  # 400
        FORBIDDEN,  # 403
        METHOD_NOT_ALLOWED,  # 405
        REQUEST_TIMEOUT,  # 408
```

With my naive eyes, I'd expect _only_ 408's to be retryable, but not 400's, 403's, or 405's. 🤷 

### Next steps

As a result of the above, I'm not sure what the the consequences would be of changing the behavior of dbt to _not_ retry `OtherHTTPRetryableError`s. I will defer to one of our adapter engineers to make a call one way or the other how we should handle this going forward.

**Comment by joellabes** [comment]
Reopening this because it has bitten me a few times this month getting ready for the hackathon. 

> With my naive eyes, I'd expect _only_ 408's to be retryable, but not 400's, 403's, or 405's. 🤷

I think this is right (backed up by [this SO post](https://stackoverflow.com/a/47841642/14007029)). 

Did we get a ruling from anyone on the adapters team? 

Would this be better as an issue on the snowflake-connector-python repo, suggesting that 408s should be the only 4xx error that are retryable?

**Comment by dbeatty10** [comment]
Thanks for re-opening @joellabes!

At the most detailed level, this seems like an issue within snowflake-connector-python itself. i.e. it is categorizing 403's, etc as being "retryable" [here](https://github.com/snowflakedb/snowflake-connector-python/blob/adb34d69a2c2819b6ea31e58558093ccc0450626/src/snowflake/connector/network.py#L177-L184) as introduced in [this](https://github.com/snowflakedb/snowflake-connector-python/commit/3a24e6231d8e7f0ee51edd8074e725817bcbbb86) commit.

It would be solved "automatically" if [snowflake-connector-python](https://github.com/snowflakedb/snowflake-connector-python) reduced the scope of HTTP codes included in `OtherHTTPRetryableError`.

Assuming they can't or won't, I'm going to re-label this as "help wanted" for a motivated community member to take on.

### Acceptance criteria
- 408 (request timeout) is retryable within dbt-snowflake
- No other 4xx codes are retryable within dbt-snowflake
