### ISSUE TITLE
[CT-1749] [Feature] Let Snowpark telemetry know that dbt is creating the sproc

### ISSUE THREAD

**Issue by dataders** [dbt-labs/dbt-snowflake#374]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Snowflake is requesting that the below line of code be added to the body of user-created python functions used to create python UDFs on behalf of users behind the scenes and have `PartnerName_ToolName="dbt"`

```python
sys._xoptions['snowflake_partner_attribution'].append("PartnerName_ToolName")
```

Below is where our template of sproc creation is implemented. It seems the implementation would be to somehow modify the function definition in `compiled_code` to also include the `sys._xoptions` call?
https://github.com/dbt-labs/dbt-snowflake/blob/e18c501175c84d5b08d66244533e636a5a04dba1/dbt/adapters/snowflake/impl.py#L199-L210

This is an example provide by the Snowflake team
```sql
create function python_udf_usage_tracking(c1 int, c2 int)
returns double
language python
runtime_version='3.8'
handler = 'PartnerTrackingTest'
as $$$$
import sys
 
def sum(a,b):
    sum=a+b
    sys._xoptions['snowflake_partner_attribution'].append("PartnerName_ToolName")
    return sum
$$$$;
```

#### We do nothing

This is one idea

#### We add a session parameter to connection creation?

Not sure if this would be helpful for the Snowpark team, that wants to track consumption...

https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/adapters/snowflake/connections.py#L284-L285
```
```

**Comment by ChenyuLInx** [comment]
Do we have to call `sys._xoptions` inside user's function? can we just do it at the very end or very beginning right after import sys?

**Comment by lostmygithubaccount** [comment]
agreed we should move it if possible to below the import instead of in user code

I don't see any reason we couldn't/shouldn't do this, would definitely check w/ @jtcohen6 to be sure

**Comment by sfc-gh-ripu** [comment]
@dataders can you please expand on the alternate solution linked? Are you suggesting dbt python models will be able to add a specific query tag, say "snowpark_python" ?

**Comment by jtcohen6** [comment]
@sfc-gh-ripu If I understand right, we're awaiting confirmation from folks on your side that it's possible to do something similar to `sys._xoptions['snowflake_partner_attribution']` (which works in UDFs) in stored procedures as well, since that's how we're currently creating + calling dbt Python models on Snowpark.

@dataders My hesitation with the `query_tag` approach is, that's something we've opened up fully to user-space configuration. Users can add/remove whatever `query_tag` they want, and it's fully visible within their own query histories. Whereas `application` or `snowflake_partner_attribution` are _just_ for use by Snowflake + partners.

**Comment by dataders** [comment]
@sfc-gh-ripu amazing! just opened up #383 as a draft. @ChenyuLInx @colin-rogers-dbt wanna take a look?
