### ISSUE TITLE
[CT-1775] Convert remaining integration tests (dbt-snowflake)

### ISSUE THREAD

**Issue by Fleid** [dbt-labs/dbt-snowflake#382]
The [integration folder](https://github.com/dbt-labs/dbt-snowflake/tree/main/tests/integration) should be emptied, all remaining tests should be converted to the new framework in the [functional folder](https://github.com/dbt-labs/dbt-snowflake/tree/main/tests/functional).

Most conversions should be ports from the core repo, others will be specific to Snowflake.

**Comment by bennylu2** [comment]
Why is it being moved from integration to functional?
