### ISSUE TITLE
[CT-1601] Support string private_key

### ISSUE THREAD

**Issue by dlecocq** [dbt-labs/dbt-snowflake#41]
### Describe the feature
Allow accepting a private_key as a string, not just a path.

### Describe alternatives you've considered
In some contexts, providing a path to the key is difficult, and allowing it to be passed a string provides another mechanism to consume that key.

As a concrete example, while using `airflow-dbt`, we would like to read credentials from `secretsmanager` and use them for authenticating into Snowflake. Normally, we would just create a temporary file with a context manager, write the private key out to the file, and use it. However, this proves awkward when using Airflow.

### Additional context
The `airflow-dbt` project allows `vars` to be templated, which means we could dynamically (and idiomatically) provide the private key contents dynamically. However, there's no clean toehold to do this using a context manager, and the ideas of 1) pre/post-hooks to clean up a temporary file for a private key, or 2) letting the private key linger in a temporary directory are pretty unappealing.

### Who will this benefit?
Predominantly `dbt` users needing to use private key auth without touching the filesystem.

### Are you interested in contributing this feature?
Definitely! I've got a MR nearly ready to go, which I will submit after submitting this issue.

**Comment by joshuataylor** [comment]
This would also be amazing for CI, such as Github where we have to create a temporary file.

**Comment by jtcohen6** [comment]
Sorry for the delay here — sure! I have no reason to oppose this. I'm going to mark this a `good first issue`. It will be tricky for us to test in our CI setup, so I'll be relying on whomever contributes this change to do some local verification as well.

**Comment by ShardPhoenix** [comment]
Hi @dlecocq, are you still planning to make a PR for this? If not I'm considering implementing it (and also adding support for bytes keys as well as strings).

**Comment by craig-infostrux** [comment]
Is this feature still being considered?

**Comment by dbeatty10** [comment]
Re-opening since https://github.com/dbt-labs/dbt-snowflake/pull/265 is an open pull request meant to implement this feature.
