### ISSUE TITLE
[CT-2086] [Bug] dbt_valid_to timestamp not consistant on update and delete rows

### ISSUE THREAD

**Issue by zqWu** [dbt-labs/dbt-snowflake#463]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

 when have both  delete and update tuples,  dbt snapshot will have different value(8 hours)  on dbt_valid_to field

### Expected Behavior

two values of column dbt_valid_to should be same, if ignore slight execution time 

### Steps To Reproduce

1. create sampel table in snowflake
<img width="257" alt="image" src="https://user-images.githubusercontent.com/7589001/218265855-152c87b2-1ab8-4a35-960a-de40d5415141.png">

here is sample data
```sql
COPY INTO raw_listings (id,
                        listing_url,
                        name,
                        room_type,
                        minimum_nights,
                        host_id,
                        price,
                        created_at,
                        updated_at)
                   from 's3://dbtlearn/listings.csv'
                    FILE_FORMAT = (type = 'CSV' skip_header = 1
                    FIELD_OPTIONALLY_ENCLOSED_BY = '"');
```
2. create snapshot.yml and  run   `dbt snapshot`
<img width="642" alt="image" src="https://user-images.githubusercontent.com/7589001/218265901-5905e7e0-a622-4bcf-aec2-c3ecc7e83a23.png">

3. in base table,  update 1 tuple and delete 1 tuple, execute in snowflake then confirm it
```sql

update AIRBNB.RAW.RAW_LISTINGS 
set MINIMUM_NIGHTS= 100, updated_at = current_timestamp() 
where id= 9991 and MINIMUM_NIGHTS=0

delete from AIRBNB.RAW.RAW_LISTINGS where id = 14325
```

4. run dbt snapshot, update tables in snowflake
except:  the two tuple(id=9991, id=14325) has same dbt_validate_to value (or very close value)
got: have timezone issue (i'm in +8 timezonee)

<img width="586" alt="image" src="https://user-images.githubusercontent.com/7589001/218266363-6e35585a-714d-4b89-b398-40fa8f459bae.png">

### Relevant log output

```shell
dbt output log

(dbt_snowflake) dormi330@dormi330:~/ws/dbt/snowflake_example01$ dbt snapshot
15:02:53  Running with dbt=1.4.1
15:02:53  Found 8 models, 0 tests, 1 snapshot, 0 analyses, 304 macros, 0 operations, 1 seed file, 3 sources, 0 exposures, 0 metrics
15:02:53  
15:02:58  Concurrency: 4 threads (target='dev')
15:02:58  
15:02:58  1 of 1 START snapshot dev.scd_raw_listings ..................................... [RUN]
15:03:02  1 of 1 OK snapshotted dev.scd_raw_listings ..................................... [success in 3.98s]
15:03:02  
15:03:02  Finished running 1 snapshot in 0 hours 0 minutes and 8.86 seconds (8.86s).
15:03:02  
15:03:02  Completed successfully
15:03:02  
15:03:02  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```

### Environment

```markdown
- OS: ubuntu 22.04
- Python: 3.10.6
- dbt-core: 1.4.1
- dbt-snowflake: 1.4.1
```

### Additional Context

dbt_valid_to of updated tuple is wrong
dbt_valid_to of delete tuple is right

**Comment by dbeatty10** [comment]
Thanks for reaching out @zqWu !

Could you try:
```
set MINIMUM_NIGHTS= 100, updated_at = to_timestamp_ntz(convert_timezone('UTC', current_timestamp()))
```

instead of:
```
set MINIMUM_NIGHTS= 100, updated_at = current_timestamp() 
```

### More info
There are two important things to always keep in mind in relation to snapshots:
1. when `updated_at` is configured, it is assumed to be represented in UTC
1. `dbt_valid_to` has the `timestamp_ntz` data type

If you search in `logs/dbt.log` for "current_timestamp()", you can see the logic that dbt uses when doing hard deletes. You will want to use the same logic when you modify `updated_at`.

#### Example of implicit timestamp conversion

In the case of dbt snapshots, `dbt_valid_to` has data type of `timestamp_ntz`.

But the data type of `current_timestamp()` is `timestamp_ltz`, so you need to take extra care in ensuring it can be cast to `timestamp_ntz` in such a way that it accurately represents UTC.

Here is an example query that shows how Snowflake implicitly converts timestamps:
```sql
-- See how Snowflake implicitly converts timestamps
select
    current_timestamp() as current_ts,
    current_timestamp()::timestamp_ntz as current_ts_bad,
    to_timestamp_ntz(convert_timezone('UTC', current_timestamp()))::timestamp_ntz as current_ts_good
;
```

---

Could you try that out and let me know how it goes?

**Comment by zqWu** [comment]
that's it,  after test, dbt_valid_to  values are same
so, that's not a bug

<img width="695" alt="image" src="https://user-images.githubusercontent.com/7589001/218709529-b528aba3-9976-4cd3-99b4-89452bda539d.png">

**Comment by dbeatty10** [comment]
That's great @zqWu !
