### ISSUE TITLE
[CT-2112] [Bug] Snyk: dependency vulnerability `snowflake-connector-python==2.8.2`

### ISSUE THREAD

**Issue by dataders** [dbt-labs/dbt-snowflake#469]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

@QMalcolm brought [Snyk Vulnerability report](https://security.snyk.io/vuln/SNYK-PYTHON-SNOWFLAKECONNECTORPYTHON-3111888) for `snowflake-connector-python==2.8.2` to our attention.

Add this to the list of reasons why we release a patch release for 1.4 where `snowflake-connector-python>=3.0.0`:

- #331
- #393

### Expected Behavior

No Snyk vulnerabilities?

### Steps To Reproduce

See Snyk report

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-snowflake:
```

**Comment by mikealfare** [comment]
Closed due to automation. This needs to be backported to `dbt-snowflake>=1.1` and then it can be marked done.

**Comment by mikealfare** [comment]
This has been patched (1.5) and backported to versions 1.1 through 1.4
