### ISSUE TITLE
[CT-2224] [Bug] Can't import a csv if it has more than one column

### ISSUE THREAD

**Issue by samsolo512** [dbt-labs/dbt-snowflake#494]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I placed two csv files under the seeds directory and ran dbt seed.  One file has a single column and imports perfectly.  The other file is identical to the first, but with one additional column and errors out with "Database Error".  The error occurs for all csv files that have more than one column.

### Expected Behavior

Both csv files should import without a problem, regardless of the number of columns in the file.

### Steps To Reproduce

1. copy csv files to seeds directory
2. activate python environment
3. navigate to dbt folder
4. run dbt seed

### Environment

```markdown
- OS: Windows 10, dbt-snowflake
- Python: 3.10.7
- dbt-core: 1.4.1
- dbt-snowflake: 1.4.1
```

### Additional Context

![2023-02-28_00h19_23](https://user-images.githubusercontent.com/7538402/221781857-03fe918c-5014-4d74-9eb4-f0c861dbf05d.png)

![2023-02-28_00h22_30](https://user-images.githubusercontent.com/7538402/221782551-f837f555-c909-4f62-9600-d96aa1051871.png)

[test_1_col.csv](https://github.com/dbt-labs/dbt-snowflake/files/10847500/test_1_col.csv)

[test_2_col.csv](https://github.com/dbt-labs/dbt-snowflake/files/10847502/test_2_col.csv)

**Comment by dbeatty10** [comment]
Thanks for reaching out @samsolo512 !

I suspect that you're seeing that error because `GROUP` is a [reserved keyword](https://docs.snowflake.com/en/sql-reference/reserved-keywords).

Wanna give a try with a different column name like `Category`?

**Comment by samsolo512** [comment]
Wow, I feel dumb.  That's exactly what it was.  Thanks for the help!

**Comment by dbeatty10** [comment]
No worries @samsolo512 -- so many things seem simple in hindsight, but aren't so obvious in the moment! Happy to help.
