### ISSUE TITLE
[ADAP-409] [Feature] Indicate when dbt is waiting for snowflake mfa

### ISSUE THREAD

**Issue by Jacob-Bishop** [dbt-labs/dbt-snowflake#535]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Print something to the console to indicate when dbt is waiting for a snowflake mfa prompt to be handled, rather than simply silently waiting until either the prompt is handled or times out. 

### Who will this benefit?

Occasionally when the coffee hasn't kicked in yet, I end up spending a few seconds staring blankly at the console before scrambling for my phone to answer the mfa prompt. I imagine I'm not the only one?

**Comment by dbeatty10** [comment]
The coffee must have kicked in ☕ -- good idea @Jacob-Bishop ! (Thanks for the visual too, gave me a good chuckle.)

I'm going to mark this as a `good_first_issue` for an interested community member to pick up.

The implementation for this will likely be logging a message within [connections.py](https://github.com/dbt-labs/dbt-snowflake/blob/d3589a9d1f1ca89c7a924f73070e150b3a0587b8/dbt/adapters/snowflake/connections.py) for the applicable `authenticator` method(s) that wait for the user to complete their MFA.

**Comment by morenoh149** [comment]
@dbeatty10 is this the best issue to get started working on? I'm looking for a good issue to contibute to dbt
