### ISSUE TITLE
[ADAP-425] [Bug] --select config.snowflake_warehouse:warehouse_name doesn't work

### ISSUE THREAD

**Issue by 0xrdt** [dbt-labs/dbt-snowflake#545]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

the selection of nodes based on their configuration is well documented on dbt for configs such as the type of materialization (example [here](https://docs.getdbt.com/reference/node-selection/test-selection-examples#more-complex-selection))

but I couldn't get it to work for the snowflake_warehouse config, for example:
`dbt ls --models config.snowflake_warehouse:warehouse_name`
will return ` The selection criterion 'config.snowflake_warehouse:warehouse_name' does not match any nodes`

even after making sure the warehouse exists and the names I defined in the config is the same as the one I defined in the selection statement

this is not exclusive do `dbt ls` other selection commands don't work like:
`dbt run --select config.snowflake_warehouse:warehouse_name`
`dbt test --select config.snowflake_warehouse:warehouse_name`

this also didn't work:
`dbt run --select config.warehouse:warehouse_name`

### Expected Behavior

I would expect dbt to return the nodes that use that warehouse **or at least throw an error saying that this type of selection isn't supported**

### Steps To Reproduce

In dbt core 1.4.1 and dbt snowflake 1.4.0, create a model like:
```
{{ config(snowflake_warehouse=my_warehouse) }}
SELECT true
```

try to run `dbt --select config.snowflake_warehouse:my_warehouse`

### Environment

```markdown
- OS: MacOS Ventura 13.2
- Python: Python 3.10.9
- dbt-core: 1.4.1
- dbt-snowflake: 1.4.0
```

**Comment by Fleid** [comment]
Hey @0xrdt, I can't reproduce the issue.

Well, I can't reproduce on the `snowflake_warehouse` configuration. If it's defined on a model, it pops up on `dbt ls --select config.snowflake_warehouse:<...>`.

There is a typo in your repro case by the way. The config value should be between 'quotes':

```SQL
{{ config(snowflake_warehouse='my_warehouse') }}
SELECT true
```

Also note that this selection process is case sensitive.

---

As for the `warehouse` profile field, it's not reachable from `dbt ls`. LS parses the content of the DAG. It doesn't load the full context from profile. @jtcohen6 to keep me honest here.

I'm intrigued as to what the underlying requirement is here? If it's to find which models haven't be given a `snowflake_warehouse` value, it can be done via something like:

```BASH
dbt ls --exclude config.snowflake_warehouse:my_warehouse config
.snowflake_warehouse:EXTRA_LARGE
```

**Comment by 0xrdt** [comment]
Hey @Fleid!

That's embarrassing... you're correct, `dbt ls --models config.snowflake_warehouse:warehouse_name` does generally work

I was testing it with `dbt ls --models config.snowflake_warehouse:warehouse_name --target prod`, so it turns out the bug is a bit different: **the bug only happens if you're passing a different target and this target points to a different warehouse**

Should I file another issue? or just update this one?

## Current Behavior
`dbt ls --models config.snowflake_warehouse:warehouse_name --target other_profile` checks for config.snowflake_warehouse in the **default** profile instead of the **other_profile**

## Expected Behavior
Just like with other configs such as `dbt ls --models config.materialized:incremental --target other_profile`, I expected that passing the target flag would point the selection to the configs from the other profile

## Why I want to do this
Mostly for housekeeping, we change warehouses **a lot** and have hundreds of models, so it's hard to know which warehouse we are actually using at a point in time

We also use macros quite heavily, so we can't just grep the files looking for the warehouse name

**Comment by 0xrdt** [comment]
we set `{{ config(materialized=get_incremental()) }}` on a couple of models, where `get_incremental()` is the following macro
```sql
{% macro get_incremental() -%}
  {%- set target_name = target.name -%}
  {%- if target_name == 'dev' or target_name == 'qa' -%}
    {{ 'view' }}
  {%- else -%}
    {{ 'incremental' }}
  {%- endif -%}
{%- endmacro %}
```

we do this in order to only materialize the tables on prod

and we use patterns like `dbt run --select config.materialized:incremental,tag:vertical_something --target prod --full-refresh` to full refresh a subset of models (while skipping "table" models)

**Comment by Fleid** [comment]
Ok, with the `get_incremental()` macro as you listed, my_model as:
```SQL
{{ config(materialized=get_incremental()) }}
SELECT true
```

I made sure to have 2 profiles in my profiles.yml (dev properly setup, prod with placeholder values):

```YAML
adap_425:
  outputs:
    dev:
      account: ...
      authenticator: externalbrowser
      database: ...
      role: ...
      schema: ...
      threads: 1
      type: snowflake
      user: ...
      warehouse: ...
    prod:
      account: prod
      database: prod
      role: prod
      schema: prod
      threads: 1
      type: snowflake
      user: prod
      warehouse: prod
  target: dev
```

Then I get:

```BASH
dbt ls --models config.materialized:incremental --target prod
adap_425.my_model

dbt ls --models config.materialized:view
adap_425.my_model
```

Which is I think the expected behavior here?
