### ISSUE TITLE
Non-deterministic tests to check query tags

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt-snowflake#55]
Unfortunately, these tests introduced by #48 appear to fail non-deterministically:
```
tests/integration/simple_seed_test/test_seed_with_query_tag.py::TestSeedWithQueryTag::test_snowflake_big_batched_seed
tests/integration/simple_snapshot_test/test_snapshot_query_tag.py::TestSnapshotWithQueryTag::test__snowflake__snapshot_with_query_tag
```

See:
- https://github.com/dbt-labs/dbt-snowflake/runs/4263981165
https://github.com/dbt-labs/dbt-snowflake/actions/runs/1480696294

These tests check to confirm that a previously run query is tagged with an appropriate `query_tag`. They pass whenever I run them locally. Could it be an issue with tests running concurrently?

**Comment by anthu** [comment]
That's a pity :(

I assume we are running into some race conditions, I didn't expect.
As I'm not that familiar with the test framework - do you have an idea for a better test? I'm happy to take on the implementation.

**Comment by jtcohen6** [comment]
@anthu Thanks for the offer! I _think_ I managed to get this sorted in #57, by using a post-hook (runs within the materialization) instead of a custom singular test that runs later on
