### ISSUE TITLE
Repair accidental change to dev-requirements

### ISSUE THREAD

**Issue by peterallenwebb** [dbt-labs/dbt-snowflake#558]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Wrong branches

### Expected Behavior

Right branches

### Steps To Reproduce

Build main

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-snowflake:
```

**Comment by dbeatty10** [comment]
Closed by https://github.com/dbt-labs/dbt-snowflake/pull/559
