### ISSUE TITLE
[ADAP-457] [Bug] Behavior of `copy_grants`

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-snowflake#567]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Opening this issue on behalf of @kevinjmccarthy as reported [here](https://github.com/dbt-labs/dbt-core/issues/7280#issuecomment-1502436707). The text that follows is copy-pasted from that report.

---
<img width="272" alt="image" src="https://user-images.githubusercontent.com/44704949/232258302-94b761b3-4459-4c3d-ac12-56b1975d801f.png">

I'm a bit confused by the solution and the behavior of `copy_grants`. I've tried adding it into my own project which uses the following versions:
```
dbt --version 
Core:
  - installed: 1.3.0
  - latest:    1.4.5 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.3.0  - Update available!
  ```
  
  in [dbt-core](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/adapters/apply_grants.sql), `copy_grants` is True by default
```jinja
{% macro copy_grants() %}
    {{ return(adapter.dispatch('copy_grants', 'dbt')()) }}
{% endmacro %}

{% macro default__copy_grants() %}
    {{ return(True) }}
{% endmacro %}
```
in [dbt-snowflake](https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/include/snowflake/macros/apply_grants.sql), `copy_grants` is False by default
```jinja
{% macro snowflake__copy_grants() %}
    {% set copy_grants = config.get('copy_grants', False) %}
    {{ return(copy_grants) }}
{% endmacro %}
```
So with this PR change, setting `copy_grants` to True ends up [setting should_revoke to True](https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/include/global_project/macros/adapters/apply_grants.sql#L47-L49) and a revoke is issued. Is this the expected behavior? Why does setting copy_grants to True cause dbt to revoke existing grants after the model is created? It seems to happen after the `copy grants` DDL is ran.

### Expected Behavior

See above

### Steps To Reproduce

See above

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-snowflake:
```

**Comment by dbeatty10** [comment]
Thanks for reporting this @kevinjmccarthy 🙏 

If you add this macro to your project, does it work as desired for you (both when `copy_grants=True` and `copy_grants=False`)?

`macros/apply_grants.sql`
```sql
{% macro should_revoke(existing_relation, full_refresh_mode=True) %}

    {% if not existing_relation %}
        {#-- The table doesn't already exist, so no grants to copy over --#}
        {{ return(False) }}
    {% elif full_refresh_mode %}
        {#-- The object is being REPLACED -- revoking grants is opposite of the copy grants user config --#}
        {{ return(not copy_grants()) }}
    {% else %}
        {#-- The table is being merged/upserted/inserted -- grants will be carried over --#}
        {{ return(True) }}
    {% endif %}

{% endmacro %}
```

**Comment by kevinjmccarthy** [comment]
Hello @dbeatty10 sorry for the long delay! I was able to run some tests.

- Apply external select grant to ROLE1
- Add dbt grant for ROLE2

### Without changes to `macros/apply_grants.sql`:
`+copy_grants: False`
- Running dbt applies the following:
  - `create or replace  view ... as ...;`
  - `grant select on ... to ROLE2;`

`+copy_grants: True`
- Apply external select grant
- Running dbt applies the following:
  - `create or replace  view ... copy grants as ...;`
  - `revoke SELECT on ... from ROLE1;`


### With changes to `macros/apply_grants.sql`:
`+copy_grants: False`
- Apply external select grant
- Running dbt applies the following:
  - `create or replace  view ... as ...;`
  - `revoke SELECT on ... from ROLE1;`
  - `grant select on ... to ROLE2;`

`+copy_grants: True`
- Apply external select grant
- Running dbt applies the following:
  - `create or replace view ... copy grants as ...;`
  - `grant select on ... to ROLE2;`

So the behavior results in a REVOKE if copy_grants = False

**Comment by dbeatty10** [comment]
Thanks for doing those manual tests @kevinjmccarthy ! 🏆

With changes to `macros/apply_grants.sql`, did the behavior of both `+copy_grants: False/True` work the way you expected?

If so, we can move forward by including those changes in a PR (including relevant functional tests).

**Comment by kevinjmccarthy** [comment]
Yes, it makes more sense to me to have the setting of copy_grants to True prevent dbt from revoking those grants. I'm unsure what the original intent of using this flag within the should_revoke macro was, but It would be good to add this behavior to the [dbt docs](https://docs.getdbt.com/reference/resource-configs/snowflake-configs#copying-grants) so it's more explicitly called out that this flag does more than just altering the DDL statement.

**Comment by dbeatty10** [comment]
Good call about the docs @kevinjmccarthy. Opened this as a result:
- https://github.com/dbt-labs/docs.getdbt.com/pull/3474
