### ISSUE TITLE
[ADAP-461] [Enhancement] Enable listing >10K objects in a schema

### ISSUE THREAD

**Issue by matt-winkler** [dbt-labs/dbt-snowflake#571]
### Current Behavior

When a [target schema contains more than 10,000 tables + views](https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/include/snowflake/macros/adapters.sql#L153), dbt throws a compilation exception. 

### Expected Behavior

Make dbt additionally robust to this situation, such that a compilation error is not triggered at an arbitrary (though imposed by Snowflake) threshold. See [here](https://docs.snowflake.com/en/sql-reference/sql/show-objects) for more details on the Snowflake limits.

### Steps To Reproduce

`dbt run` in an environment with a target schema that contains more than 10K tables / views. 

### Additional Context

Based on the [diff](https://github.com/dbt-labs/dbt-core/pull/2322/files#diff-4e52d38c66fb471207fa26868ecc11715965558734704859a52b6bcfbc5c86cfL96-L111) from when we changed the approach here last, could we:

1. Run `SHOW TERSE OBJECTS`
2. If we see 10K results
3. Fall back to querying the information schema

?

**Comment by dbeatty10** [comment]
Thanks for opening @matt-winkler !

Your suggested approach seems reasonable:
1. Run `SHOW TERSE OBJECTS`
1. If we see <10K results, use them
1. If we see >=10K results, fall back to querying the information schema

Having that many objects sounds like a recipe for sloooow-cooking, but at least we can make it _possible_.

Are you interested in contributing this, by any chance?

**Comment by matt-winkler** [comment]
@dbeatty10 yep yep here is my [PR](https://github.com/dbt-labs/dbt-snowflake/pull/572)

**Comment by dataders** [comment]
so we're deep in one of the two hard things in computer science: cache invalidation.

For the case where there's greater than ten thousand objects, it seems expensive to run a `SHOW TERSE OBJECTS` every single time `list_relations_without_caching` is called. perhaps this is better addressed with:
1. a profile-level config like `megachonk_infoschema: true`
2. a helpful warning when `n(objects)>10k` a la "consider using the `megachonk_infoschema` param?

**Comment by matt-winkler** [comment]
Well, I'm rubbish at variable naming, so hopefully we can get this one right @dataders. 

Now thinking:

- You make a good point about profile-level configs. Any thoughts on where that implementation might live?
- I think we still likely want to implement a fallback in this location in order to allow runs to continue. Whether it's profile lever or not, we've seen this limit reached in practice so (IMO) should design with that in mind.
- The louder we can be about the end-user message (i.e. raising the limit on the snowflake side, or setting this profile configuration), the better.

**Comment by matt-winkler** [comment]
@dataders @dbeatty10 I learned that `SHOW TERSE OBJECTS` in fact supports pagination. The process is: 

- Run the query once
- Capture the *last value* in the `name` field 'FOO'
- Run the query again as `in schema {{my_db}}.{{my_schema}} limit 10000 from 'FOO'`. 'FOO' acts as an offset / pagination here.
