### ISSUE TITLE
dbt Seed, throwing a error 

### ISSUE THREAD

**Issue by Rahul-Gajula** [dbt-labs/dbt-snowflake#58]
i am new to dbt, so i was trying to seed a csv file to snowflake using dbt seed command. and i am ending with this error. 

![image](https://user-images.githubusercontent.com/92009794/143449561-7212685c-220e-4bae-99ef-c3e3626cdf90.png)

**Comment by jtcohen6** [comment]
@Rahul-Gajula Welcome! Which version of dbt are you using? (Could you run `dbt --version` and copy the output here?)

It sounds like there may have a mismatch between the versions of `dbt-core` and `dbt-snowflake` that you have installed. The `get_batch_size` macro was added in dbt-core v0.21 (https://github.com/dbt-labs/dbt-core/pull/3623).

**Comment by Rahul-Gajula** [comment]
installed version: 0.20.2
   latest version: 0.21.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.21.0
  - postgres: 0.21.0
  - redshift: 0.21.0
  - snowflake: 0.21.0
  - sqlserver: 0.20.1
  - synapse: 0.20.0

**Comment by Rahul-Gajula** [comment]
is this the problem of version, or do i need to configure in dbt_project.yml. 

Just correct me if the process is right 
1. i copied the csv file to data folder of  dbt project 
2. without any configuration in the dbt_project.yml i ran dbt seed

**Comment by jtcohen6** [comment]
@Rahul-Gajula As I suspected, you have `dbt-core==0.20.2` and `dbt-snowflake==0.21.0` installed. Those versions are not mutually compatible.

If you installed dbt with `pip`, you can upgrade to the latest versions (and ensure compatibility) by running:
```
pip install dbt-snowflake --upgrade
```

**Comment by Rahul-Gajula** [comment]
yes, it worked like a charm. Thank you Jeremy, appreciate your kind help.
