### ISSUE TITLE
[ADAP-547] [Feature] Pagination to allow >10k schemas per database

### ISSUE THREAD

**Issue by jaypeedevlin** [dbt-labs/dbt-snowflake#605]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

https://github.com/dbt-labs/dbt-snowflake/issues/571 used pagination to support retrieving >10k objects in a schema.  The same pattern can be used to enable >10k schemas in a database.

I propose to use the same technique for the latter as the former (which I've confirmed Snowflake supports).

### Describe alternatives you've considered

Overriding the macro in our project.

### Who will this benefit?

Anyone using dbt at scale — specifically we run into this from time to time with our databases that create an environment per PR for dev.

### Are you interested in contributing this feature?

Yes!

**Comment by jaypeedevlin** [comment]
Bump

**Comment by ttishihara** [comment]
Hello, are there any updates for this or any new related issues?
