### ISSUE TITLE
[ADAP-584] [Bug] Non-conventional Version Check in Setup.py

### ISSUE THREAD

**Issue by DustinMoriarty** [dbt-labs/dbt-snowflake#633]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

The setup.py checks the python version using a manual condition statement. This is not conventional python packaging behavior. The package manager is responsible for checking the python version. The python version is documented in the package metadata using the python_requires property. Adding an extra check of the python version deviates from the behavior expected during python packaging. 

### Expected Behavior

Leave the python_requires setting but remove the condition block.

### Steps To Reproduce

Inspect the setup.py.

### Environment

```markdown
- OS:any
- Python:>=3.7
- dbt-core:any
- dbt-snowflake:1.6.0b2
```

**Comment by Fleid** [comment]
Removing `triage`, I agree this should be considered as part of https://github.com/dbt-labs/dbt-core/issues/6855
When it's officially added in its scope, we should flag this issue as duplicate.

**Comment by DustinMoriarty** [comment]
@Fleid : Any thoughts about merging https://github.com/dbt-labs/dbt-snowflake/pull/634 now? Do we need to wait for #6855?

**Comment by Fleid** [comment]
I would wait for #6855 - if anything else to have everything done together.
