### ISSUE TITLE
MFA Token not being cached

### ISSUE THREAD

**Issue by gnilrets** [dbt-labs/dbt-snowflake#64]
### Describe the bug
I'm trying to get Snowflake's [DUO-based MFA](https://docs.snowflake.com/en/user-guide/security-mfa.html#connecting-to-snowflake-with-mfa) working when running dbt in a linux container running on my laptop.  Technically it works, but it's not caching the token and I have to repeatedly re-authorize.  I have tried:

* Setting ALLOW_CLIENT_MFA_CACHING to true for the account
* Setting ALLOW_ID_TOKEN to true for the account
* Setting `authenticator: username_password_mfa` in profiles.yml

All that, and yet, every time I run dbt, I get 4 MFA auth requests right away, and then 1 for each model that it runs.  Obviously, this is impractical with 10-100's of models.  I'm wondering what else I might be missing, if anything.  I swear there used to be a note in Snowflake's docs that some aspect of this only worked on Mac and Windows environments, but I can't find that anymore and was hopeful that it had been resolved for linux.  Perhaps this is a dbt defect that isn't sending the right auth method to the python lib?

### System information
**The output of `dbt --version`:**
```
root@bbafbba2e1dc:/dbt-runner/dbt# dbt --version
installed version: 0.21.0
   latest version: 0.21.1

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 0.21.0
```

**The operating system you're using:**  Using a linux container built based on [this dockerfile](https://github.com/gnilrets/dbt-container-skeleton/blob/main/Dockerfile) (with some minor modifications)
```
root@bbafbba2e1dc:/dbt-runner/dbt# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"


root@bbafbba2e1dc:/dbt-runner/dbt# uname -r
5.10.47-linuxkit
```

**The output of `python --version`:**
```
root@bbafbba2e1dc:/dbt-runner/dbt# python --version
Python 3.8.12
```
**Version of snowflake connector:** `snowflake-connector-python[secure-local-storage]==2.5.1`

**Comment by tekumara** [comment]
Are you connecting using:

```
conn = snowflake.connector.connect(
    ...
    client_store_temporary_credential=True
)
```

**Comment by gnilrets** [comment]
@tekumara - No, I want this to work running it with dbt using a Snowflake warehouse.

**Comment by tekumara** [comment]
Ah yep gotcha. So if you can connect directly in Python using `client_request_mfa_token=True` and caching works, then that at least means your snowflake account is set up correct.

But it does look like dbt-snowflake is missing `client_request_mfa_token=True` when it connects (although [id token caching is enabled](https://github.com/dbt-labs/dbt-snowflake/blob/e1ee1c8d9aa3986d9ed8460750fb932f0131c310/dbt/adapters/snowflake/connections.py#L119))

**Comment by tekumara** [comment]
@gnilrets I've pushed a PR, you can install it using:
```
pip install 'dbt-snowflake @ git+https://github.com/dbt-labs/dbt-snowflake.git@refs/pull/65/head'
```

does it work for you?

**Comment by gnilrets** [comment]
Yes!  That worked.  Now I only have to authorize via MFA once and the token is even cached between dbt runs.  I also don't need to set `authenticator: username_password_mfa`.

Looking forward to when this will be released!

**Comment by jtcohen6** [comment]
@tekumara Thanks for the PR! Sounds like this is an easy win :)

**Comment by KevinKaers** [comment]
@tekumara , will this solve this issue just for Linux or on a Windows environment too?

**Comment by tekumara** [comment]
Windows doesn’t require this setting and should work already without it. Is it not for you?

**Comment by KevinKaers** [comment]
I was following this bug seeing as I mentioned it not working for me in a Windows environment through the dbt Slack.
Here's what I've done so far:

_Hi everyone,
I've been searching the web and Slack for this and still can't get it to work, so here's another shot:
Has anyone managed to reduce to number of DUO pushes needed when using user/password authentication combined with MFA and dbt CLI?
Here's what I have and did
dbt profiles is set up with local variables
ALLOW_CLIENT_MFA_CACHING on account level is set to TRUE in Snowflake
ALLOW_ID_TOKEN on account level is set to TRUE in Snowflake (to my understanding this isn't necessary, but someone hinted that this made it work for them so why no try it)
Tried enabling ALLOW_CLIENT_MFA_CACHING on user level but this generates an 'insufficient privileges' error (even though I'm using the accountadmin)
Reconnected and restarted wherever I could, still get about 9 DUO pushes when trying to run a single model.
Something I might've missed?_

**Comment by tekumara** [comment]
Which version of dbt-snowflake are you using @KevinKaers ? Are you running inside a docker container on Windows?

**Comment by KevinKaers** [comment]
@tekumara , apologies, I had some time off last week.
I am running v0.21 without any containers.

**Comment by tekumara** [comment]
@KKaers hmm on Windows I would have thought it would have already worked. Does the PR work for you?
FYI - it's now been rebased on dbt-snowflake 1.0.0 so you would need to upgrade to dbt 1.0.0 first I think.

**Comment by KKaers** [comment]
@tekumara we've upgraded to v1.0.0 2 weeks ago, so no issue there on using the PR. I just installed and tried it and still to no avail. Running just 1 model I get around 7 push requests.
I'm going to revisit some of the other individual steps & parameters to make sure I didn't miss anything, because it seems odd that this doesn't seem to be such an issue with other Windows users.
One difference I spot in other cases mentioning this is that I'm not working in a separate environment/container, but imo this shouldn't make a difference.
In any case, still thanks for your help

**Comment by JPHaus** [comment]
I'm running into this issue after upgrading & moving from a virtual env to a docker container running on Windows.

dbt --version
```
root@2c51325063d5:/dbt# dbt --version
installed version: 1.0.1
   latest version: 1.0.1

Up to date!

Plugins:
  - snowflake: 1.0.0
```

I also tried `ALTER ACCOUNT SET ALLOW_CLIENT_MFA_CACHING=TRUE;`
And tried both with and without `authenticator: username_password_mfa` inside my profiles.yml

**Comment by KKaers** [comment]
Update: for some reason, after the update I've now tried again by adding the `authentictor` to profiles.yml and it works

**Comment by JPHaus** [comment]
> Update: for some reason, after the update I've now tried again by adding the `authenticator` to profiles.yml and it works

Would you mind sharing your profiles.yml?

**Comment by KKaers** [comment]
@JPHaus , sure. below is a snippet for prod for example
Upgraded to dbt v1.0.1 and ALLOW_CLIENT_MFA_CACHING set to TRUE in Snowflake

Not sure if I missed something while still on v0.21 or if it just has been fixed since v1.0.0 (seeing as this doesn't seem to be a widespread issue, I'm guessing the former).

`  outputs:
    prod:
      type: snowflake
      threads: 4
      account: "{{ env_var('SNOWFLAKE_PR_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_PR_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PR_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_PR_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_PR_WAREHOUSE') }}"
      database: "{{ env_var('SNOWFLAKE_PR_DB') }}"
      schema: "{{ env_var('SNOWFLAKE_PR_SCHEMA') }}"
      authenticator: username_password_mfa`

**Comment by JPHaus** [comment]
> @gnilrets I've pushed a PR, you can install it using:
> 
> ```
> pip install 'dbt-snowflake @ git+https://github.com/dbt-labs/dbt-snowflake.git@refs/pull/65/head'
> ```
> 
> does it work for you?

I've tried the other things listed in the thread but this is the only thing that has worked for me.

**Comment by pedromachados** [comment]
When will https://github.com/dbt-labs/dbt-snowflake/pull/65 be merged? We also need to use MFA with username / password authentication.

**Comment by VersusFacit** [comment]
Doing some repo cleanup and wanted to leave for posterity the note that the following must be done to cache:
* form a role/user with appropriate permissions, run `alter account set allow_client_mfa_caching = true;`
* add to `profiles.yml`, `authenticator: username_password_mfa`

Both are needed to end the incessant pinging. Verified on MacOS and Linux.

**Comment by CalGrimes** [comment]
Running the following in a Snowflake worksheet solved this issue for me:
```
alter account set allow_client_mfa_caching = true;
alter account set ALLOW_ID_TOKEN = true;  
```
