### ISSUE TITLE
[ADAP-612] Always require integration tests

### ISSUE THREAD

**Issue by emmyoop** [dbt-labs/dbt-snowflake#653]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Right now out GitHub branch Protection rules don't enforce that integrations tests pass.  This is because we skip running integrations tests based on the files changes [here](https://github.com/dbt-labs/dbt-snowflake/blob/58d3cc43dabe09d4871abbdb2c5bff7e37aafd64/.github/workflows/integration.yml#L84-L92).

1. We should change the above code to a list of files we should ignore.  
  - `/.changes`
  - `/.github`
  - `README.md`
  - more?

2.  We should also implement this method from the [GitHub docs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks) so that the integrations tests either run, or, they are skipped but look like a pass so that we can require integration tests pass on the branch protection rules.

Note: Only admins can modify or see the branch protection rules

### Anything else?

This applies to `dbt-redshift` and `dbt-bigquery` as well.

**Comment by martynydbt** [comment]
duplicate
