### ISSUE TITLE
[Bug] Unable to preview varchar that contains binary due to Snowflake python adapter error

### ISSUE THREAD

**Issue by saraleon1** [dbt-labs/dbt-snowflake#66]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to preview a column that includes binary but is a varchar in Snowflake with the following error:

```
252005: Failed to convert current row, cause: 'utf-8' codec can't decode byte 0X87 in position 0: invalid start byte
```

[From this documentation](https://community.snowflake.com/s/question/0D53r00009pYNm6CAG/unable-to-query-tables-with-special-characters-using-the-python-connector-and-sqlalchemy) it appears that this is an error raised by the Snowflake python adapter. The select statement works as expected both in Snowflake directly and when doing a dbt run, but this error returns when trying to preview the query.

Also from that documentation, it appears that this can be avoided by wrapping this in the following:
`a.encode('utf-8').strip()`, which I believe needs to be done python-side, rather than snowflake-side.

<img width="848" alt="Screenshot 2021-12-07 at 3 12 21 p m" src="https://user-images.githubusercontent.com/40356588/145055259-5a27b891-0b3f-4a8b-a90a-436a5fc7d260.png">
y.

### Expected Behavior

can preview a string that contains binary, or at least have a more understandable error message

### Environment

```markdown
- dbt Cloud
- dbt: 0.20.2
```

### What database are you using dbt with?

snowflake

**Comment by saraleon1** [comment]
Sweet sounds good, thank you @jtcohen6!!

**Comment by RobMcZagBDS** [comment]
Thank you jerco !
