### ISSUE TITLE
[ADAP-632] [Dynamic Tables] Ensure our lifecycle follows the new behavior of DTs

### ISSUE THREAD

**Issue by Fleid** [dbt-labs/dbt-snowflake#667]
Make sure that the lifecycle implemented in `dbt-snowflake` follows the upcoming updates of Dynamic Tables.

## Desired Lifecycles

- Lifecycle (`dbt run`) : 
  - **If** necessary backup (exists with different materialization)
  - **If** necessary `CREATE OR REPLACE DYNAMIC TABLE` (doesn't exist)
  - **Else** 
      - Depending on `on_configuration_change`
        - `skip` :  Check status (see below), **if** `FAILED` then `ALTER DYNAMIC TABLE [ <name> ] REFRESH`
        - `fail` : **If** the options of the object in the database are different from the current model, fail the run
        - `apply` : [default] 
          - **If** the options of the object in the database are different from the current model, apply the changes (`WAREHOUSE`, `TARGET_LAG` via `ALTER` statement)
          - **else** check status (see below), **if** `FAILED` then `ALTER DYNAMIC TABLE [ <name> ] REFRESH`
 - Lifecycle (`dbt run --full-refresh`) :
   - **If** necessary backup (exists with different materialization)
   - `CREATE OR REPLACE DYNAMIC TABLE`
 
### Status check

The refresh status of a DT is obtained via the following query:

```SQL 
SELECT TOP 1 state
FROM TABLE(INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY(NAME => '...'))
ORDER BY refresh_version DESC;
```

The return code is a string [among](https://docs.snowflake.com/LIMITEDACCESS/dynamic_table_refresh_history#output):

> SCHEDULED, EXECUTING, SUCCEEDED, FAILED, CANCELLED, or SKIPPED

## Changes from previous assumptions
- Dynamic Tables are now refreshing synchronously: a DDL statement (`CREATE OR REPLACE`, `ALTER`) will now not return until the object is created and populated. It used to return immediately. Which means we don't need the `refresh_strategy` anymore
- Dynamic Tables have a new gesture to trigger a refresh manually (`ALTER DYNAMIC TABLE [ <name> ] REFRESH`), that can be used to fix a `FAILED` status caused by a potential unsupported upstream DAG operation.

**Comment by mikealfare** [comment]
At an initial scan, here's what I perceive as the gap:
- backup existing relation (I believe we just drop/replace in the current draft)
- we do not check for `failed`, but we refresh if there are no changes regardless of status, should we only refresh if the status is failed?
- I need to remove the manual refresh statement after the create/alter statements

**Comment by Fleid** [comment]
- backup existing relation (I believe we just drop/replace in the current draft)
That's for if a table exists with that name, and we want to replace it with a DT. If the DT creation fails, it should restore that table. I'm ok moving that to 1.6.x.

- we do not check for `failed`, but we refresh if there are no changes regardless of status, should we only refresh if the status is failed?
I commented on that on the other ticket ;) We don't want to refresh when it's not needed (not `failed` and no changes) - that's wasted $. Tell me if that's too late in the release to change, also ok to push to 1.6.x

- I need to remove the manual refresh statement after the create/alter statements
Yes please :)

**Comment by calleo** [comment]
Still interested. DTs are GA and among other things, they've added support for clustering: https://docs.snowflake.com/en/release-notes/2024/other/2024-04-29-dynamic-tables
