### ISSUE TITLE
[ADAP-731] Add Support for External Network Locations

### ISSUE THREAD

**Issue by davesgonechina** [dbt-labs/dbt-snowflake#709]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

The capability to allow access to [external network locations](https://docs.snowflake.com/en/LIMITEDACCESS/creating-using-external-network-access) (e.g. dbt API endpoints) is now in private preview. This feature would allow Python models in dbt to make use of external access integrations created separately in Snowflake by adding the following to the [implementation](https://github.com/dbt-labs/dbt-snowflake/blob/main/dbt/adapters/snowflake/impl.py#L196-L220):

```
external_access_integrations = parsed_model["config"].get("external_access_integrations", [])
external_access_integrations = "', '".join(pexternal_access_integrations)

`EXTERNAL_ACCESS_INTEGRATIONS = ({external_access_integration})`
```

A user would add `dbt.config(external_access_integrations = ["dbt_api_integration", "bi_tool_api_integration"])` to their Python model to use this capability.

### Describe alternatives you've considered

The alternative would be to build the UDF without using dbt.

### Who will this benefit?

At present, only Snowflake users who have use for this capability and, more importantly, have access to the Private Preview. As this feature moves to General Availability, the number of potential users grow.

The specific use case behind the creation of this issue is the desire to place the contents from the dbt Cloud API endpoint `v2/accounts/{accountId}/jobs/` into a model for operational visibility on job schedules and upcoming run times.

### Are you interested in contributing this feature?

Yes, time permitting. I've not contributed to a dbt adapter package before.

**Comment by ernestoongaro** [comment]
Hi @mikealfare -- this was closed as Done, but I see a new issue https://github.com/dbt-labs/dbt-snowflake/issues/925, was this implemented?
