### ISSUE TITLE
[ADAP-772] [Bug] Release 1.6.0 is created but missing package ghcr.io/dbt-labs/dbt-snowflake:1.6.0

### ISSUE THREAD

**Issue by philippe-boyd-maxa** [dbt-labs/dbt-snowflake#725]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Git release 1.6.0 is created but missing package ghcr.io/dbt-labs/dbt-snowflake:1.6.0

### Expected Behavior

Package ghcr.io/dbt-labs/dbt-snowflake should be created at the same time as the git release

### Steps To Reproduce

Navigate to https://github.com/dbt-labs/dbt-snowflake/releases and realise that ghcr.io/dbt-labs/dbt-snowflake:1.6.0 doesn't exist.

**Comment by dbeatty10** [comment]
Thanks for altering about this @philippe-boyd-maxa ! 🙏

There are ghcr releases for 1.6.0 for both dbt-core and dbt-postgres:
- https://github.com/dbt-labs/dbt-core/pkgs/container/dbt-core
- https://github.com/dbt-labs/dbt-postgres/pkgs/container/dbt-postgres

But we're missing 1.6.0 for these:
- https://github.com/dbt-labs/dbt-bigquery/pkgs/container/dbt-bigquery
- https://github.com/dbt-labs/dbt-spark/pkgs/container/dbt-redshift
- https://github.com/dbt-labs/dbt-snowflake/pkgs/container/dbt-snowflake
- https://github.com/dbt-labs/dbt-spark/pkgs/container/dbt-spark

We'll get these queued up for publishing.

**Comment by dbeatty10** [comment]
[ghcr.io/dbt-labs/dbt-snowflake:1.6.0](https://github.com/dbt-labs/dbt-snowflake/pkgs/container/dbt-snowflake/116465293?tag=1.6.0) is published now.
