### ISSUE TITLE
[ADAP-881] Dbt Version 1.6.1 Not Able to Authenticate with Snowflake via Private Key Config

### ISSUE THREAD

**Issue by chris-leigh-dignifi** [dbt-labs/dbt-snowflake#767]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I am able to successfully authenticate via the `private_key_path`, but when supplying the exact same key via a string using the `private_key` config in `profiles.yaml`, dbt is not able to authenticate with Snowflake. I am using an encrypted private key and currently running dbt version 1.6.1. 

### Expected Behavior

I expect dbt to be able to authenticate with Snowflake via either configuration options.

### Steps To Reproduce

1. Create new user in Snowflake with encrypted Private Key auth via Snowflake's [instructions](https://docs.snowflake.com/en/user-guide/key-pair-auth#step-1-generate-the-private-key)
2. Test access via SnowSQL (optional)
3. Supply auth parameters in dbt projects `profiles.yaml` file
_Test 1_
4. First try authenticating with the `private_key_path` config, confirm this method works
5. Then try authenticating with the `private_key` config, confirm that this method **does not** work

### Relevant log output

```shell
[0m10:50:59.238622 [error] [MainThread]: Encountered an error:
Runtime Error
  Database error while listing schemas in database "dev__lake"
  Database Error
    ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [<OpenSSLError(code=109052072, lib=13, reason=168, reason_text=wrong tag)>, <OpenSSLError(code=109576458, lib=13, reason=524554, reason_text=nested asn1 error)>])
[0m10:50:59.239026 [debug] [MainThread]: Command `dbt run` failed at 10:50:59.238975 after 1.99 seconds
[0m10:50:59.239292 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10596f460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113575e80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1135f8250>]}
```

### Environment

```markdown
- OS: MacOS Ventura Version 13.4.1
- Python: Python 3.9.18
- dbt-core: 1.6.1
- dbt-snowflake: 1.6.1
```

**Comment by chris-leigh-dignifi** [comment]
@dbeatty10 thank you for the quick response!

Yes that's correct -- I am using PEM format for my key generation. Do you happen to have any instructions on converting the private key to Base64-encoded DER format via the command line? I tried following these [instructions](https://stackoverflow.com/questions/8454677/create-privatekey-and-publickey-from-a-string-base64-encoding-with-der-format), but did not have any luck.

**Comment by dbeatty10** [comment]
Sure thing @chris-leigh-dignifi !

Unfortunately, I don't happen to have a set of instructions to do that conversion, and I haven't done that before personally.

In the meantime, I'm going to close this in favor of https://github.com/dbt-labs/dbt-snowflake/pull/671 which should be released and available by the end of October.
