### ISSUE TITLE
[ADAP-886] [Feature] Redact raw data from Duplicate Field Key Error

### ISSUE THREAD

**Issue by jaypeedevlin** [dbt-labs/dbt-snowflake#772]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

In https://github.com/dbt-labs/dbt-snowflake/pull/378, redaction was added for duplicate row DML.  We have recently discovered a second type of error — duplicate field key — which can leak sensitive data into logs.  Here's an example of what an error looks like:

```
Duplicate field key 'my raw string goes here'
```

I'd like to propose adding similar redacting to this use case.  I've also contact Snowflake to confirm whether there are other related errors we may need to handle.

### Describe alternatives you've considered

Wrap dbt and redact the logs before they hit downstream alerting tools.

### Who will this benefit?

Anyone wanting to stop data leaking into their logs.

### Are you interested in contributing this feature?

Absolutely

**Comment by dbeatty10** [comment]
Thanks for creating this issue and raising a PR @jaypeedevlin 🏆
