### ISSUE TITLE
[ADAP-902] [Bug] pip install dev-requirements only works on the second attempt

### ISSUE THREAD

**Issue by joshuataylor** [dbt-labs/dbt-snowflake#784]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Running `pip install -e . -r dev-requirements.txt` followed by `dbt debug` results in the following error:

```
+ dbt debug
02:25:50  Running with dbt=1.7.0-b2
02:25:50  dbt version: 1.7.0-b2
02:25:50  python version: 3.11.5
02:25:50  python path: /home/josh/dev/project/.venv/bin/python
02:25:50  os info: Linux-6.2.0-1011-aws-aarch64-with-glibc2.35
02:25:50  Error importing adapter: No module named 'dbt.adapters.snowflake'
02:25:50  Using profiles dir at /home/josh/.dbt
02:25:50  Using profiles.yml file at /home/josh/.dbt/profiles.yml
02:25:50  Using dbt_project.yml file at /home/josh/dev/project/dbt_project.yml
02:25:50  Configuration:
02:25:50    profiles.yml file [ERROR invalid]
02:25:50    dbt_project.yml file [OK found and valid]
02:25:50  Required dependencies:
02:25:50   - git [OK found]

02:25:50  Connection test skipped since no profile was found
02:25:50  1 check failed:
02:25:50  Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "default", target "full" invalid: Runtime Error
    Could not find adapter type snowflake!
```

This happens on MacOS ARM64 ("Apple Silicon") & Linux ARM64/AMD64 with Python 3.11.

The second time the command is run, everything works fine.

### Expected Behavior

It works on the first install.

### Steps To Reproduce

1. Clone the repository
2. Follow the steps at https://github.com/dbt-labs/dbt-snowflake/blob/main/CONTRIBUTING.md#running-dbt-snowflake-in-development
3. Run `dbt debug` in a project

### Environment

```markdown
- OS: ArchLinux/Ubuntu/MacOS
- Python: 3.11
- dbt-core: 1.7.0-b2
- dbt-snowflake: 1.7.0-b2 (main?)
```

**Comment by dbeatty10** [comment]
Good call @joshuataylor !

I think the most immediate solution would be to update the CONTRIBUTING file to include instructions like these:
```
python3 -m pip install -e . -r dev-requirements.txt
python3 -m pip install -e .
```

⚠️ Note that `pip install -e .` is duplicated twice! The 2nd one is the key one in relation to the issue you are reporting. The 1st one is to avoid dependency conflicts with the way pip's dependency resolver works.

I think this would affect all dbt adapters, so I created this tasklist to track them all: https://github.com/dbt-labs/dbt-core/issues/8678

An even better solution would be if it didn't need to be executed twice for the adapter to be seen. More helpful info here: https://github.com/dbt-labs/dbt-core/issues/8504#issuecomment-1700875518

**Comment by joshuataylor** [comment]
Great, also the [Makefile](https://github.com/dbt-labs/dbt-snowflake/blob/main/Makefile#L4) will need to be updated for `make dev`.
