### ISSUE TITLE
[ADAP-922] [Feature] Passing user's Application name to Snowflake session

### ISSUE THREAD

**Issue by v4mishra** [dbt-labs/dbt-snowflake#791]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Usually organizations need some way of tracking usage / queries to Databricks/Snowflake databases. One way of doing that is setting teams/modules name in database connection / session object (via user_agent_entry).

When we create a connection using dbt, dbt sets its own details while creating a connection to real database. 
For snowflake [see code where we are hard-coding 'dbt'](https://github.com/dbt-labs/dbt-snowflake/blob/82b2acbf36099ea28a22032e98e95dd888e90bbd/dbt/adapters/snowflake/connections.py#L350C20-L350C20) to application parameter when using snowflake python connector. Due to this we cannot override/append our details. 

dbt-databricks has a good approach. It allows setting 'DBT_DATABRICKS_INVOCATION_ENV' [which is later on appended to 'user_agent_entry' string.](https://github.com/databricks/dbt-databricks/blob/main/dbt/adapters/databricks/connections.py#L865).

Following databricks like approach in dbt-snowflake will also help us.  

### Describe alternatives you've considered

Suggestion is mentioned above. Provide a way to append additional info to 'application' variable by using any environment variable. 

### Who will this benefit?

Users who use dbt to connect to Snowflake and need some way of metering/tracking the queries/usage of Snowflake by setting an application/user_agent string. 

### Anything else?

I asked similar query here as well - https://discourse.getdbt.com/t/application-name-or-useragent-info-to-snowflake/10031

**Comment by dbeatty10** [comment]
What do you think @dataders ? The solution for dbt-databricks is in https://github.com/databricks/dbt-databricks/pull/155. If we did something similar within dbt-snowflake, the relevant environment variable would be `DBT_SNOWFLAKE_INVOCATION_ENV`. Generalizing this approach to other adapters could either be an environment variable like `DBT_{adapter}_INVOCATION_ENV` or maybe a fully generalized name like `DBT_USER_AGENT_ENTRY`.
