### ISSUE TITLE
[ADAP-925] [Feature] Support docker image arm64

### ISSUE THREAD

**Issue by aka-ao** [dbt-labs/dbt-snowflake#794]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

We are running dbt on an arm64 cpu machine.
Are there any plans to create an official image for the arm64 platform?

### Describe alternatives you've considered

Currently there are no official images that support arm64, so we build our own images as follows
```
FROM python

RUN pip install -U pip
RUN pip install dbt-core==1.6.1
RUN pip install dbt-snowflake==1.6.2
...
```

### Who will this benefit?

All those running dbt docker images on the arm64 platform

**Comment by dbeatty10** [comment]
We don't have plans to provide official images across a variety of platforms, so building your own is the way to go 👍
