### ISSUE TITLE
[ADAP-1031] [Bug] send_anonymous_usage_stats ignored for python models

### ISSUE THREAD

**Issue by Dikootje** [dbt-labs/dbt-snowflake#830]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When running python models against Snowflake a telemetry header is added to the procedure. 

```python
import sys
sys._xoptions['snowflake_partner_attribution'].append("dbtLabs_dbtPython")
```

Even with the profiles.yml configured in a what that should prevent this: 
```yml
config:
  send_anonymous_usage_stats: false
```

### Expected Behavior

When send_anonymous_usage_status is set to false I expect the telemetry snippet not to be inserted in the python code that is send to Snowflake. 

https://github.com/dbt-labs/dbt-snowflake/blob/f67098d585b90303e5a946e363ba860ce9efe78c/dbt/adapters/snowflake/impl.py#L222

### Steps To Reproduce

1. Using dbt-core v1.7.0 and dbt-snowflake v1.7.0
2. Create any python model
3. Execute using Snowflake
4. Look up the query in the snowflake query history

### Environment

```markdown
- OS: any
- Python: 3.11
- dbt-core: 1.7.0
- dbt-snowflake: 1.7.0
```

### Additional Context

When auditing the Snowflake query log, we've discovered that dbt usage is being tracked even when this is set specifically to false in the dbt `profiles.yml`.

**Comment by mikealfare** [comment]
Re-opening for backport
