### ISSUE TITLE
[ADAP-1045] [CT-3413] Vulnerability in cryptography package used in DBT

### ISSUE THREAD

**Issue by DanielMawdsley96** [dbt-labs/dbt-snowflake#845]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Snyk vulnerability found 

 ✗ Denial of Service (DoS) [Medium Severity][https://security.snyk.io/vuln/SNYK-PYTHON-CRYPTOGRAPHY-6050294] in cryptography@41.0.5

    introduced by dbt-snowflake@1.7.0 > snowflake-connector-python@3.4.0 > cryptography@41.0.5 and 1 other path(s)

### Expected Behavior

No vulnerability 

### Steps To Reproduce

Run snyk on GitHub repo containing DBT project

### Environment

```markdown
- OS: windows 
- Python: 3.11
- dbt: 1.7
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

@mikealfare: We need to pin this in `setup.py` with a lower bound as it's a transient dependency. It appears bumping `snowflake-connector-python` may also resolve this, but we need to regression test that change given our surface area on that package, so pinning `cryptography` directly would be faster for now.

**Comment by mikealfare** [comment]
This has been backported and merged, but not yet released. I'm reopening to make sure we confirm this is released.

**Comment by VersusFacit** [comment]
Well today I learned we have multiple install channels to manage for the repo 😬
