### ISSUE TITLE
[ADAP-1046] [CT-3418] [Bug] dbt python model logging not working with snowflake

### ISSUE THREAD

**Issue by manishkundu** [dbt-labs/dbt-snowflake#846]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

dbt python model logging statement not able to put logs inside snowflake event table.

Model Name: Logging_test.py
Code: 
```python
import snowflake.snowpark as snowpark
import snowflake.snowpark.functions as f
from snowflake.snowpark.functions import *
import logging
logger = logging.getLogger("dbt_logger")
logger.info("******Inside Logging module.******")
def model(dbt, session):
    session.sql(f"""ALTER SESSION SET LOG_LEVEL = INFO""").collect()
    logger.info("******Logging start.******")
    df=session.sql(f"""select current_user() as session_user,current_role() as session_role""")
    logger.info("******Logging End.******")
    return df
```

### Expected Behavior

dbt model should put log in event table 

### Steps To Reproduce

1. Set snowflake event table : https://docs.snowflake.com/en/developer-guide/logging-tracing/event-table-setting-up
2.  Set connection param in dbt profile.yml file
3.  run the dbt python model : dbt run -model logging_test
4. check event table in snowflake setup in step1 
    ```sql
    SELECT
	    RECORD['severity_text']::STRING log_level ,
	    VALUE::STRING message ,
	    RESOURCE_ATTRIBUTES['snow.query.id']::STRING query_id
    FROM
	    DXRX_OPERATIONS.LOGGING.EVENTS
    WHERE
	    SCOPE['name']::STRING = 'dbt_logger'
    ORDER BY
	    "TIMESTAMP" DESC;
    ```
5. Check query history in snowsight and get the dbt generated store procedure (Sql query start with  WITH logging_test__dbt_sp AS PROCEDURE ())
6. Execute the procedure from snowsight and wait for few minute
7. Execute the step 4 query again , it will show you logs generated by Snowsight query id 
8. dbt generated query id logs missing from event table ----(it should be there )

### Environment

```markdown
- OS: window
- Python: 3.8
- dbt:1.7.2
```

### Which database adapter are you using with dbt?

snowflake

### Additional Context

While executing the dbt generated store procedure from snowsight, it's working fine and insert logs in event log table

**Comment by wenbaolicat** [comment]
any progress?

**Comment by mikealfare** [comment]
@manishkundu @wenbaolicat I've tried quite a lot of combinations of settings and I believe this comes down to the settings on `TRACE LEVEL`. This setting may be defaulted to `OFF` for the dbt runner, but is on for your account or your session. I'll put together a minimal reproduction and attach it as a PR, but in the meantime, could you please verify that `TRACE_LEVEL` is not set to 'OFF` somehow? Alternatively, if you have permissions on your account, could you run `ALTER ACCOUNT SET TRACE LEVEL = ALWAYS;` and re-run your example to see if the issue persists?

**Comment by mikealfare** [comment]
@manishkundu @wenbaolicat It looks like the `TRACE_LEVEL` parameter was not the issue. Apparently it takes well over a minute for the event table to reflect logs and I must have been picking up logs from prior settings. The issue seems to be that setting `LOG_LEVEL` within the stored procedure creation does not work. However, I was able to get it to work if I used a pre-hook as this runs prior to the stored procedure:

```python
import logging

import snowflake.snowpark as snowpark
import snowflake.snowpark.functions as f
from snowflake.snowpark.functions import *


logger = logging.getLogger("dbt_logger")
logger.info("******Inside Logging module.******")


def model(dbt, session: snowpark.Session):
    # To use: GRANT MODIFY SESSION LOG LEVEL ON ACCOUNT TO ROLE <DBT_ROLE>;
    dbt.config(pre_hook='ALTER SESSION SET LOG_LEVEL=INFO;')
    logger.info("******Logging start.******")
    df=session.sql(f"select current_user() as session_user, current_role() as session_role")
    logger.info("******Logging End.******")
    return df
```

Please let me know if this is still not working for you.

**Comment by FilipByren** [comment]
@mikealfare could you elaborate a bit what you mean with `pre-hook`. Do you set the code above in `on-run-start:` or is the example you show enough to get the logging to work, with no additional pre-hook setup?

**Comment by FilipByren** [comment]
@mikealfare thank you for spotting a fix, do you know how to resolve the following issue I have when running the `pre_hook`

```
  Insufficient privileges to operate on  'SESSION'
```

I understand I have Insufficient privileges on the set role, but im not sure what type of access I should give it to make session alteration to work. Any ideas?
