### ISSUE TITLE
[ADAP-1066] 1.7.1 - Security Fix Release not available as Container Image

### ISSUE THREAD

**Issue by gilcrest** [dbt-labs/dbt-snowflake#862]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I would expect that container images would be part of your release process, however, it seems that may not be the case. I cannot find the new release (dbt-snowflake 1.7.1) at [https://github.com/dbt-labs/dbt-snowflake/pkgs/container/dbt-snowflake](https://github.com/dbt-labs/dbt-snowflake/pkgs/container/dbt-snowflake).

### Expected Behavior

Considering this is a security fix, I'm hoping to get dbt-snowflake 1.7.1 as a container image as soon as possible.

### Steps To Reproduce

Navigate to [https://github.com/dbt-labs/dbt-snowflake/pkgs/container/dbt-snowflake](https://github.com/dbt-labs/dbt-snowflake/pkgs/container/dbt-snowflake) - look for release 1.7.1

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-snowflake:
```

**Comment by VersusFacit** [comment]
Hi, there! Thanks for pointing out the omission. I believe I have corrected that seeing as the new releases are present in our GitHub repository. I'm gonna close out this issue but feel free to re-open it if you run into any additional issues.

<img width="719" alt="image" src="https://github.com/dbt-labs/dbt-snowflake/assets/67295367/e2f33275-6620-4e0c-8653-c0c89fda0bf6">

**Comment by gilcrest** [comment]
Great - thank you!!
