### ISSUE TITLE
[ADAP-1076] [Feature] [Dynamic Tables] Add new parameter properties (REFRESH_MODE, INITIALIZE)

### ISSUE THREAD

**Issue by sfc-gh-lkoh** [dbt-labs/dbt-snowflake#868]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

New parameters have been added to dynamic tables, please add them so that users can add them to the config and use the parameters.
The parameters are REFRESH_MODE, INITIALIZE.
![image](https://github.com/dbt-labs/dbt-snowflake/assets/111027281/9333318a-6832-4160-856e-70b294cdf586)

### Anything else?

https://docs.snowflake.com/en/sql-reference/sql/create-dynamic-table

**Comment by matsavage** [comment]
Is there a timeline for this getting into main?
