### ISSUE TITLE
[ADAP-1084] [Feature] Support Column Comment

### ISSUE THREAD

**Issue by yassun7010** [dbt-labs/dbt-snowflake#876]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

A related to https://github.com/dbt-labs/dbt-core/issues/9198 .

Support column comment information on dbt-snowflake.

### Who will this benefit?

People considering transitioning to dbt.

Especially for those who initially define data in sources and gradually migrate to models.

### Are you interested in contributing this feature?

Yes

### Anything else?

Also see https://github.com/dbt-labs/dbt-core/pull/9230

**Comment by dbeatty10** [comment]
Similarly to https://github.com/dbt-labs/dbt-core/issues/9198 and https://github.com/dbt-labs/dbt-codegen/issues/119, closing this per https://github.com/dbt-labs/dbt-core/issues/9198#issuecomment-1877377688.
