### ISSUE TITLE
[ADAP-1088] Run details - rows_affected always return 1 

### ISSUE THREAD

**Issue by AvivVegh** [dbt-labs/dbt-snowflake#878]
### Is this a new bug in dbt-snowflake?

- [X] I believe this is a new bug in dbt-snowflake
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

After running dbt build -> run_results.json is generated 
the field rows_affected in each models is always 1 

### Expected Behavior

the field rows_affected in each models should be the number of insert rows 

### Steps To Reproduce

1. dbt build
2. target folder
3. open run_results.json
4. look for rows_affected

### Environment

```markdown
- OS:
- Python: 3.9
- dbt-core: 1.7.4
- dbt-snowflake: 1.7.1
```

**Comment by dbeatty10** [comment]
Thanks for reporting this @AvivVegh !

And thank you for pointing out the underlying issue @b-per 🙏

Closing this in favor of https://github.com/snowflakedb/snowflake-connector-python/issues/645
