### ISSUE TITLE
[ADAP-1091] [Feature] Include Snowflake session_id in run results response 

### ISSUE THREAD

**Issue by akaul** [dbt-labs/dbt-snowflake#881]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

As a dbt user, I want to be able to quickly look up information about the set of queries associated with a dbt model run rather than just the final create/insert/update statement. While the query_id is powerful, the session_id can provided richer information back to Snowflake users to under the full lifecycle of queries executed.

To implement this feature, we could extend the `SnowflakeAdapterResponse` to include the session_id.

```
@dataclass
class SnowflakeAdapterResponse(AdapterResponse):
    query_id: str = ""
    session_id: str = ""
```

### Describe alternatives you've considered

Similar to the alternatives discussed within https://github.com/dbt-labs/dbt-snowflake/issues/7, a post-hook might work, but not give an idea of the full lifecycle in case of failures. 

### Who will this benefit?

This would help dbt-snowflake users to more effectively debug and understand why their queries succeeded or failed.

### Are you interested in contributing this feature?

Yes!

**Comment by instazackwu** [comment]
+1, being able to easily see all connected queries in a given model instead of just the final query would be be very helpful in debugging / potential optimization!
