### ISSUE TITLE
[Feature] Release connections in seperate threads instead of the main thread

### ISSUE THREAD

**Issue by joshuataylor** [dbt-labs/dbt-snowflake#902]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

dbt may open many connections if using multiple threads, I think it's 1 connection per thread.

This can take time to close each one, especially with higher latency. For me in Perth, AU to us-east-1 (~270ms latency), this can take 1-2 seconds per connection to close, and I use 16 connections to Snowflake in certain circumstances for workloads like tests/views/etc.

Right now these connections are closed in the main thread, so they are sequentially closed.

This one was a bit faster, only taking *9 seconds* to close these.

```
09:58:41.915229 [debug] [Thread-17 ]: Finished running node model.somewarehouse.sometable
09:58:41.917674 [debug] [MainThread]: Connection 'master' was properly closed.
09:58:41.917986 [debug] [MainThread]: Connection list_databasename_schemaname_a' was left open.
09:58:41.918205 [debug] [MainThread]: On list_databasename_schemaname_a: Close
09:58:42.511680 [debug] [MainThread]: Connection 'list_databasename_schemaname_aaa' was left open.
09:58:42.512028 [debug] [MainThread]: On list_databasename_schemaname_b: Close
09:58:43.093075 [debug] [MainThread]: Connection 'list_databasename_schemaname_b' was left open.
09:58:43.093389 [debug] [MainThread]: On list_databasename_schemaname_c: Close
09:58:43.671073 [debug] [MainThread]: Connection 'list_databasename_schemaname_c' was left open.
09:58:43.671399 [debug] [MainThread]: On list_databasename_schemaname_d: Close
09:58:44.246076 [debug] [MainThread]: Connection 'list_databasename_schemaname_d' was left open.
09:58:44.246407 [debug] [MainThread]: On list_databasename_schemaname_e: Close
09:58:44.817599 [debug] [MainThread]: Connection 'list_databasename_schemaname_e' was left open.
09:58:44.817936 [debug] [MainThread]: On list_databasename_schemaname_f: Close
09:58:45.415476 [debug] [MainThread]: Connection 'list_databasename_schemaname_f' was left open.
09:58:45.415810 [debug] [MainThread]: On list_databasename_schemaname_g: Close
09:58:45.994771 [debug] [MainThread]: Connection 'list_databasename_schemaname_g' was left open.
09:58:45.995112 [debug] [MainThread]: On list_databasename_schemaname_h: Close
09:58:46.569317 [debug] [MainThread]: Connection 'list_databasename_schemaname_h' was left open.
09:58:46.569638 [debug] [MainThread]: On list_databasename_schemaname_i: Close
09:58:47.149916 [debug] [MainThread]: Connection 'list_databasename_schemaname_i' was left open.
09:58:47.150251 [debug] [MainThread]: On list_databasename_schemaname_j: Close
09:58:47.744290 [debug] [MainThread]: Connection 'list_databasename_schemaname_j' was left open.
09:58:47.744612 [debug] [MainThread]: On list_databasename_schemaname_k: Close
09:58:48.400242 [debug] [MainThread]: Connection 'model.somewarehouse.sometable' was left open.
09:58:48.400571 [debug] [MainThread]: On model.somewarehouse.sometable: Close
09:58:48.977163 [debug] [MainThread]: Connection 'list_databasename_schemaname_l' was left open.
09:58:48.977487 [debug] [MainThread]: On list_databasename_schemaname_kkk: Close
09:58:49.562825 [debug] [MainThread]: Connection 'list_databasename_schemaname_l' was left open.
09:58:49.563157 [debug] [MainThread]: On list_databasename_schemaname_l: Close
09:58:50.158305 [debug] [MainThread]: Connection 'list_databasename_schemaname_m' was left open.
09:58:50.740682 [debug] [MainThread]: On list_dev_model_josh_full_m: Close
```

This adds ~9 seconds to runs, which is incredibly annoying from a DX perspective, where you're re-running these.

This issue also occurs when running against a single model, as it opens threads/connections for different kinds of queries dbt may perform.

Instead, could this be moved to a thread based approach, so using the existing Threadpool to the amount of used threads each connection is closed

### Describe alternatives you've considered

Waiting? ;-)

### Who will this benefit?

Developers wanting a faster development cycle, instead of waiting for dbt to close connections.

### Are you interested in contributing this feature?

Yes

**Comment by amychen1776** [comment]
At this time, we will not be prioritizing this request.
