### ISSUE TITLE
[Bug] Add test for 9682 in core against 1.8 and fix replace MV macros

### ISSUE THREAD

**Issue by VersusFacit** [dbt-labs/dbt-snowflake#912]
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

1. No test for this [core fix](https://github.com/dbt-labs/dbt-core/pull/9682/files).

2. Replace macros for materialized view generate SQL. Currently the create statement is missing from what is sent to Redshift which leads to `query empy` error.

Sample logs of test failure [here](https://github.com/dbt-labs/dbt-snowflake/actions/runs/8074717833/job/22060478598?pr=913)
```
FAILED tests/functional/adapter/test_ephemeral.py::TestEphemeralMultiSnowflake::test_ephemeral_multi - assert "createorrepl...er='Female');" == 'createview"d...=\'Female\');'
FAILED tests/functional/adapter/dynamic_table_tests/test_dynamic_tables_basic.py::TestSnowflakeDynamicTableBasic::test_dynamic_table_replaces_table - AssertionError: dbt exit state did not match expected
FAILED tests/functional/adapter/dynamic_table_tests/test_dynamic_tables_basic.py::TestSnowflakeDynamicTableBasic::test_dynamic_table_replaces_view - AssertionError: dbt exit state did not match expected
```

### Expected Behavior

Have a test for the internal variables! 

Proper materialized view SQL generates and passes the tests.

### Steps To Reproduce

To trigger the test failure, integrate the fix [here](https://github.com/dbt-labs/dbt-core/pull/9682/files) into your branch, then watch integration tests fail. Open logger and you'll find the malformed query that jumps straight to `backup` without a `create` predicate.

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-redshift:
```

**Comment by Fleid** [comment]
Hey @VersusFacit, moving this to `unestimated`, but should it be `in progress` in a sprint?

**Comment by mikealfare** [comment]
Re-opening for backports
