### ISSUE TITLE
[Feature] Implement EXTERNAL_ACCESS_INTEGRATION and secrets in submit_python_job

### ISSUE THREAD

**Issue by Lindblomsebastian** [dbt-labs/dbt-snowflake#927]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-snowflake functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Propagate `external_access_integration` and `secrets` from the dbt config into the procedure being created when submitting a python model. 

Solves https://github.com/dbt-labs/dbt-snowflake/issues/925

### Describe alternatives you've considered

Extracting `external_access_integration` and `secrets` from the dbt config and propagate it to the `common_procedure_call` in https://github.com/dbt-labs/dbt-snowflake/blob/f0cbea2a47cae7b7d6d6ce750faaafa33e0d3ced/dbt/adapters/snowflake/impl.py#L225 IF they are passed in the config. 

### Who will this benefit?

This will solve https://github.com/dbt-labs/dbt-snowflake/issues/925

### Are you interested in contributing this feature?

Yes

**Comment by dbeatty10** [comment]
Consolidated into https://github.com/dbt-labs/dbt-snowflake/issues/925
