### ISSUE TITLE
[CT-239] Add `black` formatter and precommit hooks

### ISSUE THREAD

**Issue by leahwicz** [dbt-labs/dbt-snowflake#95]
Following the changes in `dbt-core`, let's add the `black` formatter and precommit hooks to the repo.

Follow the example done in `dbt-core`:
- Example precommit hook PR: https://github.com/dbt-labs/dbt-core/pull/4639
- Example formatter PR: https://github.com/dbt-labs/dbt-core/pull/4697

CC: @iknox-fa for questions

**Comment by VersusFacit** [comment]
![image](https://user-images.githubusercontent.com/67295367/160697735-be7a8741-ff54-4d3f-9f56-f2f7a89a5d2d.png)

I forgot to put "close" in the PR explicitly so the issue needs a manual close.
