### ISSUE TITLE
[CT-301] [Spike] Perf improvements for single show terse call for each database

### ISSUE THREAD

**Issue by leahwicz** [dbt-labs/dbt-snowflake#98]
Spike on this ticket and the perf improvement that can be gained: https://github.com/dbt-labs/dbt-snowflake/issues/83

Exit criteria: Will we see a perf improvement by making this change? Is it worth investing in?

**Comment by jtcohen6** [comment]
Shared initial findings in https://github.com/dbt-labs/dbt-snowflake/issues/83#issuecomment-1072331707
